import type { ActionType } from "../types/workflow.js";

export type ActionCapability =
  | "implemented"
  | "implemented_partial_requires_validation"
  | "graph_internal";

export const actionCapabilities: Record<ActionType, ActionCapability> = {
  navigate: "implemented",
  wait: "implemented",
  random_wait: "implemented",
  input_text: "implemented_partial_requires_validation",
  clear_input: "implemented_partial_requires_validation",
  click: "implemented_partial_requires_validation",
  find_element: "implemented_partial_requires_validation",
  scroll: "implemented_partial_requires_validation",
  select_option: "implemented_partial_requires_validation",
  press_key: "implemented",
  hotkey: "implemented",
  hover: "implemented_partial_requires_validation",
  double_click: "implemented_partial_requires_validation",
  right_click: "implemented_partial_requires_validation",
  drag_and_drop: "implemented_partial_requires_validation",
  focus_element: "implemented_partial_requires_validation",
  blur_element: "implemented_partial_requires_validation",
  type_sequence: "implemented_partial_requires_validation",
  set_clipboard: "implemented",
  paste_clipboard: "implemented_partial_requires_validation",
  check: "implemented_partial_requires_validation",
  uncheck: "implemented_partial_requires_validation",
  toggle_checkbox: "implemented_partial_requires_validation",
  select_radio: "implemented_partial_requires_validation",
  upload_file: "implemented_partial_requires_validation",
  submit_form: "implemented_partial_requires_validation",
  select_custom_option: "implemented_partial_requires_validation",
  set_contenteditable: "implemented_partial_requires_validation",
  extract_text: "implemented_partial_requires_validation",
  extract_attribute: "implemented_partial_requires_validation",
  extract_input_value: "implemented_partial_requires_validation",
  extract_table: "implemented_partial_requires_validation",
  extract_list: "implemented_partial_requires_validation",
  count_elements: "implemented_partial_requires_validation",
  extract_regex_matches: "implemented_partial_requires_validation",
  take_screenshot: "implemented",
  write_text_file: "implemented_partial_requires_validation",
  go_back: "implemented",
  go_forward: "implemented",
  reload: "implemented",
  open_new_tab: "implemented",
  switch_tab: "implemented",
  close_tab: "implemented",
  accept_dialog: "implemented_partial_requires_validation",
  dismiss_dialog: "implemented_partial_requires_validation",
  wait_for_download: "implemented_partial_requires_validation",
  set_variable: "implemented",
  set_json_variables: "implemented",
  assert_element: "implemented_partial_requires_validation",
  assert_text: "implemented_partial_requires_validation",
  graph_noop: "graph_internal",
  if_condition: "graph_internal",
  router_condition: "graph_internal",
  random_choice: "graph_internal",
  repeat_times: "graph_internal",
  repeat_for_each: "graph_internal",
  retry_block: "graph_internal",
  switch_condition: "graph_internal",
  while_loop: "graph_internal",
  repeat_until: "graph_internal",
  try_catch: "graph_internal",
  fallback_block: "graph_internal",
  break_loop: "graph_internal",
  continue_loop: "graph_internal",
  stop_workflow: "graph_internal",
  transform_variable: "graph_internal",
  update_number_variable: "graph_internal",
  update_text_variable: "graph_internal",
  update_flag_variable: "graph_internal",
  update_list_variable: "graph_internal",
  update_object_variable: "graph_internal",
  assert_output: "graph_internal",
  domain_allowlist: "graph_internal",
  check_conditions: "graph_internal",
  calculate_value: "graph_internal",
  set_cookie: "implemented",
  clear_cookies: "implemented",
  set_viewport: "implemented",
  set_geolocation: "implemented",
  set_extra_headers: "implemented",
  grant_permission: "implemented",
  execute_js: "implemented",
  wait_for_request: "implemented",
  wait_for_response: "implemented",
  block_request: "implemented",
  mock_response: "implemented",
  set_local_storage: "implemented",
  set_session_storage: "implemented",
  get_current_url: "implemented",
};

export const allActionTypes = Object.keys(actionCapabilities) as ActionType[];

export function isActionVisibleInPrimaryPalette(actionType: ActionType) {
  const capability = actionCapabilities[actionType];
  return capability === "implemented" || capability === "implemented_partial_requires_validation";
}
