import type { ActionType } from "../../../types/workflow";
import { actionLabels, allActionOptions } from "../../../lib/workflowUi";
import type {
  BilingualStepHelp,
} from "./stepHelpTypes";
import { enrichStepHelpContent } from "./stepHelpEnrichment";
import { englishStepHelpContent, phaseOneEnglishStepHelpContent } from "./stepHelpContent.en";
import { vietnameseStepHelpContent, phaseOneVietnameseStepHelpContent } from "./stepHelpContent.vi";

const graphInternalActionTypes = [
  "graph_noop",
  "switch_condition",
  "router_condition",
  "while_loop",
  "repeat_until",
  "try_catch",
  "fallback_block",
  "break_loop",
  "continue_loop",
  "transform_variable",
  "assert_output",
  "domain_allowlist",
  "check_conditions",
  "calculate_value",
  "update_list_variable",
  "set_text_variable",
  "append_text",
  "prepend_text",
  "replace_text",
  "trim_text",
  "change_text_case",
  "slice_text",
  "regex_extract",
  "get_text_length",
  "check_text_empty",
  "check_text_contains",
  "check_text_regex_matches",
  "create_empty_list",
  "create_list_manual",
  "split_text_to_list",
  "generate_number_range",
  "add_to_list",
  "remove_from_list_by_index",
  "remove_from_list_by_value",
  "merge_lists",
  "get_list_item",
  "get_list_length",
  "slice_list",
  "join_list",
  "filter_list",
  "map_list_property",
  "sort_reverse_list",
  "execute_list_script",
  "check_list_empty",
  "check_list_contains",
  "check_list_any_match",
  "check_list_all_match",
  "create_empty_object",
  "create_object_manual",
  "parse_json_to_object",
  "set_object_property",
  "remove_object_property",
  "merge_objects",
  "rename_object_property",
  "get_object_property",
  "get_object_keys",
  "get_object_values",
  "stringify_object",
  "execute_object_script",
  "check_object_key_exists",
  "check_object_empty",
] as const satisfies readonly ActionType[];

type GraphInternalActionType = (typeof graphInternalActionTypes)[number];

const graphInternalStepHelpContent = Object.fromEntries(
  graphInternalActionTypes.map((actionType) => [
    actionType,
    graphInternalHelp(actionLabels[actionType]),
  ]),
) as Record<GraphInternalActionType, BilingualStepHelp>;

function graphInternalHelp(label: string): BilingualStepHelp {
  return {
    vi: {
      title: `Trợ giúp ${label}`,
      summary:
        "Action nội bộ do graph compiler tạo ra từ node logic hoặc node điều phối đã lưu.",
      useWhen: [
        "Giữ workflow cũ tương thích khi payload đã chứa action nội bộ này.",
        "Ưu tiên chỉnh logic bằng graph node tương ứng thay vì thêm action này trực tiếp.",
      ],
      fields: [{ name: "Config", description: "Cấu hình được sinh từ graph node tương ứng." }],
      examples: [`${label}: được tạo khi graph compile workflow.`],
      commonMistakes: ["Thêm trực tiếp action nội bộ thay vì dùng node graph dễ làm workflow khó đọc."],
    },
    en: {
      title: `${label} Help`,
      summary:
        "Internal executable action generated by the graph compiler from saved logic or orchestration nodes.",
      useWhen: [
        "Keep older workflows compatible when a payload already contains this internal action.",
        "Prefer editing the matching graph node instead of adding this action directly.",
      ],
      fields: [{ name: "Config", description: "Configuration generated from the matching graph node." }],
      examples: [`${label}: generated when the graph compiles the workflow.`],
      commonMistakes: ["Adding internal actions directly makes workflows harder to reason about."],
    },
  };
}

const mergedStepHelpContent: Record<ActionType, BilingualStepHelp> = {} as any;

// Populate baseStepHelpContent
for (const key of Object.keys(englishStepHelpContent) as ActionType[]) {
  mergedStepHelpContent[key] = {
    vi: vietnameseStepHelpContent[key],
    en: englishStepHelpContent[key],
  };
}

// Populate phaseOneStepHelpContent
for (const key of Object.keys(phaseOneEnglishStepHelpContent) as ActionType[]) {
  mergedStepHelpContent[key] = {
    vi: phaseOneVietnameseStepHelpContent[key],
    en: phaseOneEnglishStepHelpContent[key],
  };
}

// Populate graphInternalStepHelpContent
for (const key of Object.keys(graphInternalStepHelpContent) as ActionType[]) {
  mergedStepHelpContent[key] = graphInternalStepHelpContent[key as GraphInternalActionType];
}

// Populate fallback help content for any undocumented actions to prevent crash
for (const key of allActionOptions) {
  if (!mergedStepHelpContent[key]) {
    const label = actionLabels[key] || key;
    mergedStepHelpContent[key] = {
      vi: {
        title: `${label} Help`,
        summary: `Tài liệu hướng dẫn cho hành động ${label}.`,
        useWhen: [`Khi cần thực hiện hành động ${label} trong workflow.`],
        fields: [
          {
            name: "Output name",
            description: "Tên của biến đầu ra để lưu kết quả.",
            details: ["Lưu kết quả chạy của action này để các bước sau sử dụng."],
          },
        ],
        examples: [`Sử dụng node ${label} trong luồng xử lý.`],
        commonMistakes: [],
      },
      en: {
        title: `${label} Help`,
        summary: `Help guide for the ${label} action.`,
        useWhen: [`When you need to perform the ${label} action in your workflow.`],
        fields: [
          {
            name: "Output name",
            description: "Name of the output variable to store results.",
            details: ["Stores the output value generated by this action for downstream steps."],
          },
        ],
        examples: [`Use the ${label} node in your flow.`],
        commonMistakes: [],
      },
    };
  }
}

export const stepHelpContent: Record<ActionType, BilingualStepHelp> =
  enrichStepHelpContent(mergedStepHelpContent);
