import type { StepHelpContent } from "./stepHelpTypes";
import {
  elementHelpVi,
  variableHelpVi,
  xpathField,
  iframeField,
  waitUntilField,
  timeoutField,
  scrollTimeoutField,
} from "./stepHelpContentHelpers";

export const vietnameseStepHelpContent: Record<string, StepHelpContent> = {
  navigate: {
    title: "Trợ giúp Navigate",
    summary: "Mở một URL và chờ trang tải theo điều kiện bạn chọn.",
    useWhen: ["Dùng ở đầu workflow để đi tới trang cần tự động hóa.", "Dùng khi click trước đó chuyển sang trang mới và bạn muốn điều hướng trực tiếp."],
    fields: [
      { name: "URL", description: "Địa chỉ trang web đầy đủ, nên có https:// hoặc http://." },
      { name: "Wait until", description: "Load chờ tải cơ bản; DOMContentLoaded chờ HTML sẵn sàng; Network idle chờ mạng yên hơn." },
      { name: "Timeout ms", description: timeoutField.vi },
    ],
    examples: ["URL: https://example.com/login", "Wait until: Load, Timeout ms: 30000"],
    commonMistakes: ["Thiếu https:// ở đầu URL.", "Chọn Network idle cho trang có request chạy liên tục có thể làm step chờ lâu."],
  },
  wait: {
    title: "Trợ giúp Wait",
    summary: "Chờ một điều kiện xảy ra trước khi chạy step tiếp theo.",
    useWhen: ["Dùng khi bạn biết chính xác cần chờ gì trước khi chạy step tiếp theo.", "Dùng để chờ element hiện, biến mất, URL đổi, text xuất hiện, hoặc trang tải."],
    fields: [
      { name: "Condition", description: "Điều kiện cần chờ: thời gian, element, text, URL, hoặc page load." },
      { name: "Duration ms", description: "Số mili-giây cần chờ khi Condition là Duration." },
      { name: "XPath", description: "XPath của element cần kiểm tra khi Condition là element_*." },
      { name: "Text", description: "Đoạn chữ cần thấy trên trang khi Condition là Text visible." },
      { name: "URL contains", description: "Đoạn URL cần xuất hiện khi Condition là URL contains." },
      { name: "Timeout ms", description: timeoutField.vi },
    ],
    examples: ["Condition: Element visible, XPath: //*[@id='result']", "Condition: URL contains, URL contains: /dashboard"],
    commonMistakes: ["Dùng Duration cố định trong khi Wait element visible sẽ ổn định hơn.", "XPath phải trỏ đúng element cần kiểm tra."],
  },
  random_wait: {
    title: "Trợ giúp Random Wait",
    summary: "Chờ một khoảng thời gian ngẫu nhiên trong ngưỡng min/max trước khi chạy step tiếp theo.",
    useWhen: ["Dùng khi cần nhịp chạy tự nhiên hơn giữa các thao tác.", "Dùng thay cho Wait duration cố định khi muốn mỗi lần chạy có độ trễ khác nhau."],
    fields: [
      { name: "Minimum wait ms", description: "Ngưỡng thấp nhất, tính bằng mili-giây." },
      { name: "Maximum wait ms", description: "Ngưỡng cao nhất, tính bằng mili-giây; phải lớn hơn hoặc bằng Minimum wait ms." },
    ],
    examples: ["Minimum wait ms: 500, Maximum wait ms: 1500"],
    commonMistakes: ["Đặt maximum nhỏ hơn minimum.", "Dùng random wait để che lỗi timing thay vì chờ điều kiện cụ thể khi có thể dùng Wait element/text/URL."],
  },
  input_text: {
    title: "Trợ giúp Fill Field",
    summary: "Nhập text vào input, textarea, hoặc element có thể nhập liệu.",
    useWhen: ["Dùng cho form đăng nhập, search box, textarea, hoặc field cần nhập dữ liệu.", "Dùng khi cần hỗ trợ iframe, wait nâng cao, hoặc nhập giống người dùng hơn."],
    fields: [
      { name: "XPath", description: xpathField.vi },
      { name: "Text", description: "Nội dung cần nhập vào field." },
      { name: "Clear before input", description: "Yes sẽ xóa nội dung cũ trước khi nhập." },
      { name: "Typing mode", description: "Set value đặt giá trị nhanh; Type keys gõ từng phím giống người dùng hơn." },
      { name: "Iframe XPath", description: iframeField.vi },
      { name: "Delay ms", description: "Độ trễ giữa các phím khi dùng Type keys." },
      { name: "Wait until", description: waitUntilField.vi },
      { name: "Timeout ms", description: timeoutField.vi },
    ],
    examples: ["XPath: //*[@name='email']", "Iframe XPath: //*[@id='login-frame'], XPath: //*[@name='email']"],
    commonMistakes: ["XPath trỏ vào label hoặc div bọc ngoài thay vì input thật.", "Element trong iframe cần nhập cả Iframe XPath."],
  },
  clear_input: {
    title: "Trợ giúp Clear Input",
    summary: "Xóa nội dung trong một field nhập liệu.",
    useWhen: ["Dùng trước khi nhập lại text nếu field có sẵn giá trị.", "Dùng để reset search box hoặc textarea."],
    fields: [
      { name: "XPath", description: xpathField.vi },
      { name: "Iframe XPath", description: iframeField.vi },
      { name: "Wait until", description: waitUntilField.vi },
      { name: "Timeout ms", description: timeoutField.vi },
      { name: "Method", description: "Select all dùng Ctrl/Cmd+A; Backspace xóa bằng phím; DOM value đặt giá trị rỗng trực tiếp." },
    ],
    examples: ["XPath: //*[@name='email'], Method: Select all"],
    commonMistakes: ["XPath phải trỏ tới field nhập liệu, không phải text hiển thị."],
  },
  click: {
    title: "Trợ giúp Click",
    summary: "Click vào một element như button, link, checkbox giả lập, hoặc menu.",
    useWhen: ["Dùng để bấm nút Submit, mở dropdown, chọn tab, hoặc click link.", "Dùng Real click khi muốn giống hành vi người dùng nhất."],
    fields: [
      { name: "Target source", description: "Use locator hiện field locator trực tiếp; Use Find Element ref chỉ dùng Target ref từ node Find Element trước đó." },
      { name: "Target ref", description: "Tên output của Find Element, ví dụ current_like. Khi có Target ref, action bỏ qua locator fields." },
      { name: "XPath", description: xpathField.vi },
      { name: "Mode", description: "Real click dùng chuột thật của browser; Force DOM click gọi click() trực tiếp khi element khó nhận chuột." },
      { name: "Click count", description: "Single click hoặc double click." },
      { name: "Button", description: "Nút chuột trái, phải, hoặc giữa." },
      { name: "Iframe XPath", description: iframeField.vi },
      { name: "Scroll into view", description: "Yes sẽ đưa element vào vùng nhìn thấy trước khi click." },
      { name: "Block / Inline", description: "Vị trí căn element khi scroll into view." },
      { name: "Position", description: "Điểm click trên element. Offset cho phép nhập tọa độ X/Y." },
      { name: "Offset X / Offset Y", description: "Tọa độ click tính từ góc trên trái element khi Position là Offset." },
      { name: "Wait until", description: waitUntilField.vi },
      { name: "Timeout ms", description: timeoutField.vi },
    ],
    examples: ["Target source: Use locator, XPath: //*[@type='submit']", "Target source: Use Find Element ref, Target ref: current_like"],
    commonMistakes: ["XPath trỏ vào text bên trong button thay vì button có thể click.", "Đã chọn Target ref thì Target visibility/contains/index của locator không còn tác dụng."],
  },
  find_element: {
    title: "Trợ giúp Find Element",
    summary: "Tìm một element khớp locator, lọc/rank theo viewport, rồi lưu ref ngắn hạn cho step sau như Click.",
    useWhen: ["Dùng khi nhiều nút giống nhau tồn tại trong DOM nhưng bạn muốn chọn nút đang nằm trong màn hình.", "Dùng trước Click với Target ref để tách logic chọn element khỏi logic click."],
    fields: [
      { name: "Target locator", description: "Locator thật của các element ứng viên, ví dụ button Like trong mọi article." },
      { name: "Output name", description: "Tên ref runtime để step sau dùng qua Target ref." },
      { name: "In viewport", description: "Required chỉ chọn element đang giao với viewport hiện tại." },
      { name: "Rank", description: "Nearest viewport center chọn ứng viên gần tâm màn hình nhất; Largest visible area chọn ứng viên đang lộ nhiều nhất." },
    ],
    examples: ["Target locator: article button[aria-label^='Like video'][aria-pressed='false']", "Output name: current_like, Rank: Nearest viewport center"],
    commonMistakes: ["Dùng Target index thay vì Rank khi feed scroll/virtualize có thể click sai bài.", "Để In viewport off sẽ quay lại hành vi chọn phần tử đầu DOM."],
  },
  scroll: {
    title: "Trợ giúp Scroll",
    summary: "Cuộn trang theo pixel, đưa element có sẵn vào vùng nhìn thấy, hoặc cuộn để tìm element lazy-load.",
    useWhen: ["Dùng Page Scroll khi cần cuộn một lượng pixel cố định.", "Dùng Scroll To Element khi element đã có trên trang nhưng nằm ngoài màn hình.", "Dùng Scroll Until Element Visible khi cần cuộn trang để lazy-load tạo element."],
    fields: [
      { name: "Mode", description: "Page Scroll và các mode target dùng gesture gồm nhiều wheel pulse nhỏ, pause ngắn trong gesture và pause random dài hơn giữa các gesture." },
      { name: "Scroll style", description: "Human-like chia Page Scroll thành nhiều pulse/pause; Smooth single wheel gửi một wheel gesture đúng số pixel." },
      { name: "Direction", description: "Hướng cuộn Page Scroll hoặc hướng tìm kiếm của Scroll Until Element Visible: down, up, right, hoặc left." },
      { name: "Pixels", description: "Số pixel cho Page Scroll hoặc mỗi lần cuộn tìm kiếm. Thử 250-800 tùy trang." },
      { name: "Target locator", description: "Element đích cho Scroll To Element hoặc Scroll Until Element Visible." },
      { name: "Iframe XPath", description: "Chọn iframe trên trang cha nếu target nằm trong iframe legacy XPath." },
      { name: "Timeout ms", description: scrollTimeoutField.vi },
    ],
    examples: ["Mode: Page Scroll, Direction: Down, Pixels: 500", "Mode: Scroll To Element, Iframe XPath: //*[@id='main-frame'], Target locator: //h2[normalize-space(.)='Ready']", "Mode: Scroll Until Element Visible, Direction: Down, Pixels: 700, Target locator: lazy card"],
    commonMistakes: ["Nếu element nằm trong iframe, cần Iframe XPath của iframe và target bên trong iframe.", "Scroll To Element cần target đã tồn tại trong DOM; dùng Scroll Until Element Visible cho lazy-load.", "Target scroll tự tính chunk/pause human-like; không cần cấu hình step/pause thủ công."],
  },
  select_option: {
    title: "Trợ giúp Select Option",
    summary: "Chọn một option trong thẻ select/dropdown HTML.",
    useWhen: ["Dùng cho dropdown native như country, category, status.", "Không dùng cho dropdown custom bằng div; trường hợp đó thường cần Click."],
    fields: [
      { name: "XPath", description: "XPath của thẻ select, không phải option." },
      { name: "Match by", description: "Label chọn theo chữ hiển thị; Value chọn theo thuộc tính value." },
      { name: "Value", description: "Nhãn hoặc value của option cần chọn, tùy Match by." },
      { name: "Iframe XPath", description: iframeField.vi },
      { name: "Wait until", description: waitUntilField.vi },
      { name: "Timeout ms", description: timeoutField.vi },
    ],
    examples: ["XPath: //*[@name='country'], Match by: Label, Value: Vietnam"],
    commonMistakes: ["XPath trỏ vào option thay vì select.", "Dropdown custom không phải thẻ select sẽ không dùng được step này."],
  },
  press_key: {
    title: "Trợ giúp Press Key",
    summary: "Bấm một phím đơn trên keyboard.",
    useWhen: ["Dùng để bấm Enter, Tab, Escape, ArrowDown sau một step khác.", "Dùng khi website phản ứng với phím thay vì click."],
    fields: [{ name: "Key", description: "Tên phím cần bấm, ví dụ Enter, Tab, Escape, ArrowDown." }],
    examples: ["Key: Enter", "Key: Escape"],
    commonMistakes: ["Step này bấm một phím; tổ hợp phím như Control+S nên dùng Hotkey."],
  },
  hotkey: {
    title: "Trợ giúp Hotkey",
    summary: "Bấm một tổ hợp phím.",
    useWhen: ["Dùng cho Ctrl+S, Ctrl+A, Cmd+K, Alt+Enter.", "Dùng khi app web có shortcut keyboard."],
    fields: [{ name: "Keys", description: "Nhập các phím cách nhau bằng dấu +, ví dụ Control+S hoặc Meta+K." }],
    examples: ["Keys: Control+S", "Keys: Meta+K"],
    commonMistakes: ["Trên macOS, phím Command thường là Meta.", "Không thêm khoảng trắng thừa nếu không cần."],
  },
  hover: {
    title: "Trợ giúp Hover",
    summary: "Di chuột lên một element.",
    useWhen: ["Dùng để mở menu hover, tooltip, hoặc reveal button ẩn.", "Dùng trước Click nếu button chỉ hiện sau khi hover."],
    fields: [
      { name: "XPath", description: xpathField.vi },
      { name: "Iframe XPath", description: iframeField.vi },
      { name: "Wait until", description: waitUntilField.vi },
      { name: "Timeout ms", description: timeoutField.vi },
    ],
    examples: ["XPath: //*[@aria-label='User menu']"],
    commonMistakes: ["Hover chỉ di chuột, không click.", "Nếu menu mở bằng click, dùng Click thay vì Hover."],
  },
  get_current_url: {
    title: "Trợ giúp Get Current URL",
    summary: "Lấy URL trang hiện tại và lưu vào system.current_url.",
    useWhen: ["Dùng khi cần lấy URL, query params, hoặc path segments của trang hiện tại."],
    fields: [
      { name: "Output", description: "Dữ liệu URL được lưu vào system.current_url với các field: href, origin, protocol, hostname, port, pathname, search, hash, params, segments, base." },
    ],
    examples: [],
    commonMistakes: ["Đảm bảo trang đã navigate xong trước khi lấy URL."],
  },
};

export const phaseOneVietnameseStepHelpContent: Record<string, StepHelpContent> = {
  double_click: elementHelpVi("Double Click", "click hai lần", "double-click"),
  right_click: elementHelpVi("Right Click", "click chuột phải", "context menu"),
  focus_element: elementHelpVi("Focus Element", "focus vào element", "keyboard input"),
  blur_element: elementHelpVi("Blur Element", "bỏ focus khỏi element", "validation"),
  paste_clipboard: elementHelpVi("Paste Into Field", "dán clipboard vào field", "paste"),
  check: elementHelpVi("Check", "bật checkbox", "checkbox"),
  uncheck: elementHelpVi("Uncheck", "tắt checkbox", "checkbox"),
  toggle_checkbox: elementHelpVi("Toggle Checkbox", "đảo trạng thái checkbox", "checkbox"),
  select_radio: elementHelpVi("Select Radio", "chọn radio", "radio"),
  upload_file: elementHelpVi("Upload File", "upload file", "file"),
  submit_form: elementHelpVi("Submit Form", "submit form", "submit"),
  select_custom_option: elementHelpVi("Select Custom Option", "chọn option trong custom dropdown", "combobox"),
  set_contenteditable: elementHelpVi("Set Contenteditable", "nhập nội dung contenteditable", "editor"),
  extract_text: elementHelpVi("Extract Text", "lấy text", "output"),
  extract_attribute: elementHelpVi("Extract Attribute", "lấy attribute", "output"),
  extract_input_value: elementHelpVi("Extract Input Value", "lấy giá trị input", "output"),
  extract_table: elementHelpVi("Extract Table", "lấy bảng", "output"),
  extract_list: elementHelpVi("Extract List", "lấy danh sách", "output"),
  count_elements: elementHelpVi("Count Elements", "đếm số lượng phần tử", "output"),
  extract_regex_matches: {
    title: "Trợ giúp Extract Regex Matches",
    summary: "Đọc một output đã có, lấy các đoạn khớp regex, rồi lưu danh sách match vào output mới hoặc output hiện có.",
    useWhen: ["Dùng sau Extract Text hoặc Extract List khi cần lọc URL, username, mã đơn, hoặc token từ text đã capture."],
    fields: [
      { name: "Source output", description: "Tên output đầu vào cần đọc, ví dụ post_text hoặc comment_text." },
      { name: "Pattern", description: "Regex dùng để tìm các match trong Source output." },
      { name: "Flags", description: "Regex flags như g, i, m; g sẽ được dùng để lấy nhiều match." },
      { name: "Output name", description: "Tên output lưu danh sách match." },
      { name: "Append", description: "Bật để thêm match vào danh sách output hiện có thay vì ghi đè." },
      { name: "Dedupe", description: "Bật để giữ mỗi match một lần trong danh sách output." },
    ],
    examples: ["Source output: comment_text, Pattern: @[A-Za-z0-9._-]+, Output name: tiktok_targets"],
    commonMistakes: ["Pattern sai cú pháp sẽ làm validation fail.", "Tắt Append trong loop sẽ chỉ giữ kết quả vòng lặp cuối."],
  },
  go_back: elementHelpVi("Go Back", "quay lại trang trước", "history"),
  go_forward: elementHelpVi("Go Forward", "đi tới trang sau", "history"),
  reload: elementHelpVi("Reload", "tải lại tab hiện tại", "browser"),
  open_new_tab: elementHelpVi("Open New Tab", "mở tab mới", "tab"),
  click_and_switch_tab: elementHelpVi("Click & Switch Tab", "click và chuyển sang tab mới", "open-tab"),
  switch_tab: elementHelpVi("Switch Tab", "chuyển tab", "tab"),
  close_tab: elementHelpVi("Close Tab", "đóng tab", "tab"),
  accept_dialog: elementHelpVi("Accept Dialog", "đồng ý dialog", "dialog"),
  dismiss_dialog: elementHelpVi("Dismiss Dialog", "hủy dialog", "dialog"),
  wait_for_download: elementHelpVi("Wait For Download", "chờ file tải xong", "download"),
  write_text_file: {
    title: "Trợ giúp Write Text File",
    summary: "Ghi một output thành file text trong thư mục evidence của run và lưu đường dẫn artifact vào output.",
    useWhen: ["Dùng ở cuối workflow để xuất danh sách URL, username, log ngắn, hoặc dữ liệu đã capture."],
    fields: [
      { name: "Source output", description: "Tên output cần ghi ra file." },
      { name: "Path", description: "Tên file artifact an toàn, ví dụ tiktok-usernames.txt." },
      { name: "Separator", description: "Ký tự nối các item khi Source output là array; dùng \\n cho mỗi item một dòng." },
      { name: "Trailing newline", description: "Bật để thêm newline cuối file." },
      { name: "Output name", description: "Tên output lưu đường dẫn relative của file evidence." },
    ],
    examples: ["Source output: tiktok_targets, Path: tiktok-usernames.txt, Output name: tiktok_username_file"],
    commonMistakes: ["Path chỉ là tên file artifact, không phải đường dẫn filesystem.", "Source output trống sẽ tạo file rỗng."],
  },
  set_variable: elementHelpVi("Set Variables", "lưu biến", "variable"),
  set_json_variables: elementHelpVi("Set JSON Variables", "lưu biến JSON", "variable"),
  update_number_variable: variableHelpVi("Update Number Variable", "thực hiện phép toán trên biến số"),
  set_number_variable: {
    title: "Trợ giúp Set Number Variable",
    summary: "Đặt giá trị trực tiếp cho một biến số.",
    useWhen: ["Dùng để khởi tạo một biến đếm hoặc biến lưu trữ giá trị số."],
    fields: [
      { name: "Result variable", description: "Tên biến số đầu ra cần lưu." },
      { name: "Value", description: "Giá trị số cần đặt (có thể nhập mẫu template dạng {{biến}})." },
    ],
    examples: ["Result variable: item_count, Value: 10"],
    commonMistakes: ["Nhập chuỗi văn bản không thể chuyển thành số làm giá trị lưu bị lỗi."],
  },
  generate_random_number: {
    title: "Trợ giúp Generate Random Number",
    summary: "Tạo một số ngẫu nhiên (số nguyên hoặc số thập phân) trong khoảng min/max.",
    useWhen: ["Dùng khi cần giả lập thời gian trễ ngẫu nhiên hoặc tạo dữ liệu số ngẫu nhiên."],
    fields: [
      { name: "Result variable", description: "Tên biến đầu ra để lưu số ngẫu nhiên tạo được." },
      { name: "Minimum value", description: "Giá trị nhỏ nhất của khoảng ngẫu nhiên." },
      { name: "Maximum value", description: "Giá trị lớn nhất của khoảng ngẫu nhiên." },
      { name: "Generate integer only", description: "Bật để chỉ tạo số nguyên; tắt để tạo số thập phân." },
    ],
    examples: ["Result variable: rand_delay, Minimum value: 5, Maximum value: 15, Generate integer only: Yes"],
    commonMistakes: ["Đặt giá trị tối thiểu lớn hơn giá trị tối đa."],
  },
  parse_text_to_number: {
    title: "Trợ giúp Parse Text to Number",
    summary: "Chuyển đổi một chuỗi văn bản thành giá trị số, có hỗ trợ giá trị dự phòng nếu lỗi.",
    useWhen: ["Dùng sau khi cào văn bản (ví dụ giá tiền, số lượng) từ trang web và muốn chuyển thành số để tính toán."],
    fields: [
      { name: "Source text", description: "Chuỗi văn bản nguồn cần phân tích." },
      { name: "Fallback value", description: "Giá trị dự phòng nếu phân tích thất bại." },
      { name: "Result variable", description: "Tên biến đầu ra lưu số sau khi phân tích." },
    ],
    examples: ["Source text: {{outputs.price_text}}, Fallback value: 0, Result variable: parsed_price"],
    commonMistakes: ["Chuỗi nguồn chứa ký tự đặc biệt như kí hiệu tiền tệ ($) mà chưa loại bỏ trước khi phân tích."],
  },
  math_operation: {
    title: "Trợ giúp Math Operation",
    summary: "Thực hiện các phép tính toán học cơ bản (cộng, trừ, nhân, chia, v.v.) hoặc nâng cao (abs, sqrt, min, max).",
    useWhen: ["Dùng khi cần cộng dồn biến đếm, tính tổng, hiệu hoặc so sánh tìm min/max."],
    fields: [
      { name: "Operand 1", description: "Toán hạng thứ nhất (số hoặc biến)." },
      { name: "Operation", description: "Phép toán cần thực hiện (add, subtract, multiply, divide, modulo, power, abs, sqrt, min, max)." },
      { name: "Operand 2", description: "Toán hạng thứ hai (bỏ qua với abs và sqrt)." },
      { name: "Result variable", description: "Tên biến lưu kết quả phép tính." },
    ],
    examples: ["Operand 1: {{outputs.counter}}, Operation: Add, Operand 2: 1, Result variable: counter"],
    commonMistakes: ["Chia cho số 0 trong phép chia."],
  },
  round_number: {
    title: "Trợ giúp Round Number",
    summary: "Làm tròn số theo các chế độ round (gần nhất), floor (xuống) hoặc ceil (lên) với số chữ số thập phân chỉ định.",
    useWhen: ["Dùng để làm sạch số sau các phép tính chia hoặc số thập phân phức tạp."],
    fields: [
      { name: "Source number", description: "Số nguồn cần làm tròn." },
      { name: "Rounding mode", description: "Chế độ làm tròn (round, floor, ceil)." },
      { name: "Decimal places", description: "Số lượng chữ số thập phân muốn giữ lại." },
      { name: "Result variable", description: "Tên biến lưu số sau khi làm tròn." },
    ],
    examples: ["Source number: {{outputs.math_result}}, Rounding mode: Round, Decimal places: 2"],
    commonMistakes: ["Nhập số chữ số thập phân là số âm."],
  },
  format_number: {
    title: "Trợ giúp Format Number",
    summary: "Định dạng số thành chuỗi văn bản (dạng số thập phân, phần trăm, hoặc tiền tệ) theo ngôn ngữ/địa phương.",
    useWhen: ["Dùng khi cần hiển thị số đẹp ra báo cáo hoặc định dạng giá tiền chuẩn trước khi xuất file."],
    fields: [
      { name: "Source number", description: "Số nguồn cần định dạng." },
      { name: "Format style", description: "Kiểu định dạng (decimal, percent, currency)." },
      { name: "Decimal places", description: "Số chữ số thập phân." },
      { name: "Currency code", description: "Mã tiền tệ (ví dụ USD, VND) nếu kiểu định dạng là Currency." },
      { name: "Locale", description: "Mã quốc gia/ngôn ngữ (ví dụ en-US, vi-VN)." },
      { name: "Result variable", description: "Tên biến lưu chuỗi văn bản sau định dạng." },
    ],
    examples: ["Source number: 1234.5, Format style: Currency, Currency code: VND, Locale: vi-VN"],
    commonMistakes: ["Mã tiền tệ hoặc locale không hợp chuẩn quốc tế làm hàm định dạng báo lỗi."],
  },
  compare_numbers: {
    title: "Trợ giúp Compare Numbers",
    summary: "So sánh hai số để lấy kết quả đúng/sai (boolean).",
    useWhen: ["Dùng làm điều kiện trong các khối rẽ nhánh If hoặc vòng lặp."],
    fields: [
      { name: "Operand 1", description: "Toán hạng thứ nhất." },
      { name: "Comparison operator", description: "Toán tử so sánh (gt, gte, lt, lte, eq, neq)." },
      { name: "Operand 2", description: "Toán hạng thứ hai." },
      { name: "Result variable", description: "Biến lưu kết quả so sánh (true/false)." },
    ],
    examples: ["Operand 1: {{outputs.price}}, Comparison operator: gt, Operand 2: 100, Result variable: is_expensive"],
    commonMistakes: ["So sánh số với một chuỗi văn bản chưa parse có thể dẫn đến kết quả so sánh sai."],
  },
  check_number_range: {
    title: "Trợ giúp Check Number Range",
    summary: "Kiểm tra xem một số có nằm trong khoảng min/max chỉ định hay không.",
    useWhen: ["Dùng để lọc dữ liệu số hoặc kiểm tra điều kiện giới hạn."],
    fields: [
      { name: "Number value", description: "Số cần kiểm tra." },
      { name: "Minimum bound", description: "Giới hạn dưới." },
      { name: "Maximum bound", description: "Giới hạn trên." },
      { name: "Inclusive bounds", description: "Bật để bao gồm cả biên (min <= value <= max)." },
      { name: "Result variable", description: "Biến lưu kết quả kiểm tra (true/false)." },
    ],
    examples: ["Number value: {{outputs.age}}, Minimum bound: 18, Maximum bound: 60, Result variable: is_working_age"],
    commonMistakes: ["Đặt biên dưới lớn hơn biên trên."],
  },
  check_number_property: {
    title: "Trợ giúp Check Number Property",
    summary: "Kiểm tra tính chất của số (chẵn, lẻ, số nguyên, số dương, số âm).",
    useWhen: ["Dùng để xác định tính chất số học của biến trước khi thực hiện phép toán thích hợp."],
    fields: [
      { name: "Number value", description: "Số cần kiểm tra." },
      { name: "Property to check", description: "Tính chất cần kiểm tra (even, odd, integer, positive, negative)." },
      { name: "Result variable", description: "Biến lưu kết quả kiểm tra (true/false)." },
    ],
    examples: ["Number value: {{outputs.item_index}}, Property to check: Even, Result variable: is_even_row"],
    commonMistakes: ["Kiểm tra tính chất chẵn/lẻ của một số thập phân."],
  },
  update_text_variable: variableHelpVi("Update Text Variable", "thực hiện xử lý chuỗi trên biến chữ"),
  set_boolean_variable: variableHelpVi("Boolean: Set Value", "gán giá trị boolean"),
  generate_random_boolean: variableHelpVi("Boolean: Random", "tạo boolean ngẫu nhiên"),
  parse_to_boolean: variableHelpVi("Boolean: Convert Value", "chuyển đổi sang boolean"),
  boolean_logical_op: variableHelpVi("Boolean: Logical Op", "thực hiện phép toán logic boolean"),
  compare_booleans: variableHelpVi("Boolean: Compare", "so sánh hai giá trị boolean"),
  check_boolean_property: variableHelpVi("Boolean: Check Property", "kiểm tra thuộc tính boolean"),
  update_flag_variable: variableHelpVi("Update Flag Variable", "cập nhật biến flag"),
  update_list_variable: variableHelpVi("Update List Variable", "thực hiện thao tác mảng trên biến danh sách"),
  assert_element: elementHelpVi("Assert Element", "kiểm tra element", "assert"),
  assert_text: elementHelpVi("Assert Text", "kiểm tra text", "assert"),
  graph_noop: elementHelpVi("Graph No-op", "đánh dấu luồng graph", "logic"),
  if_condition: elementHelpVi("If Condition", "rẽ nhánh", "logic"),
  router_condition: elementHelpVi("Router Condition", "router case đầu tiên", "logic"),
  random_choice: elementHelpVi("Random Choice", "chọn một nhánh theo weight", "logic"),
  repeat_times: elementHelpVi("Repeat Times", "lặp số lần", "loop"),
  repeat_for_each: elementHelpVi("Repeat For Each", "lặp từng item", "loop"),
  retry_block: elementHelpVi("Retry Block", "thử lại block", "retry"),
  stop_workflow: elementHelpVi("Stop Workflow", "dừng workflow", "stop"),
  set_cookie: elementHelpVi("Set Cookie", "đặt cookie", "cookie"),
  clear_cookies: elementHelpVi("Clear Cookies", "xóa cookie", "cookie"),
  set_viewport: elementHelpVi("Set Viewport", "đổi kích thước viewport", "device"),
  set_geolocation: elementHelpVi("Set Geolocation", "đổi vị trí", "geo"),
  set_extra_headers: elementHelpVi("Set Extra Headers", "thêm header", "headers"),
  grant_permission: elementHelpVi("Grant Permission", "cấp quyền", "permission"),
  execute_js: elementHelpVi("Execute JS", "chạy JavaScript nâng cao", "advanced"),
  wait_for_request: elementHelpVi("Wait For Request", "chờ request mạng", "network"),
  wait_for_response: elementHelpVi("Wait For Response", "chờ response mạng", "network"),
  block_request: elementHelpVi("Block Request", "chặn request khớp mẫu", "network"),
  mock_response: elementHelpVi("Mock Response", "giả lập response khớp mẫu", "network"),
  set_local_storage: elementHelpVi("Set Local Storage", "đặt localStorage", "storage"),
  set_session_storage: elementHelpVi("Set Session Storage", "đặt sessionStorage", "storage"),
  take_screenshot: {
    title: "Trợ giúp Take Screenshot",
    summary: "Chụp ảnh trang hiện tại và lưu đường dẫn vào output nếu có Output name.",
    useWhen: ["Dùng để lưu bằng chứng màn hình sau một thao tác quan trọng."],
    fields: [
      { name: "Path", description: "Đường dẫn file PNG cần ghi." },
      { name: "Output name", description: "Tên biến output để lưu lại đường dẫn ảnh." },
      { name: "Full page", description: "Yes chụp toàn trang; No chụp viewport hiện tại." },
    ],
    examples: ["Path: /tmp/workflow-result.png, Output name: screenshot_path"],
    commonMistakes: ["Thư mục cha của Path phải tồn tại.", "File cũ cùng đường dẫn sẽ bị ghi đè."],
  },
  drag_and_drop: {
    title: "Trợ giúp Drag and Drop",
    summary: "Kéo một element nguồn và thả vào element đích.",
    useWhen: ["Dùng để sắp xếp card, kéo item vào vùng drop, hoặc thao tác UI dạng kanban."],
    fields: [
      { name: "Source selection", description: "Chọn locator trực tiếp hoặc ref từ Find Element cho element cần kéo." },
      { name: "Source ref", description: "Output name của Find Element khi Drag source dùng ref runtime." },
      { name: "Source locator", description: "Locator của element cần kéo." },
      { name: "Drop target source", description: "Chọn locator trực tiếp hoặc ref từ Find Element cho vùng/element đích." },
      { name: "Drop target ref", description: "Output name của Find Element khi Drop target dùng ref runtime." },
      { name: "Target locator", description: "Locator của vùng hoặc element đích để thả." },
      { name: "Destination position", description: "Vị trí thả trong target: tâm target, phần trăm bên trong target, hoặc offset pixel từ góc trái trên của target." },
      { name: "X percent", description: "Tọa độ ngang trong target khi Destination position là Percent inside target." },
      { name: "Y percent", description: "Tọa độ dọc trong target khi Destination position là Percent inside target." },
      { name: "X offset px", description: "Số pixel ngang tính từ góc trái trên của target khi dùng Pixel offset." },
      { name: "Y offset px", description: "Số pixel dọc tính từ góc trái trên của target khi dùng Pixel offset." },
    ],
    examples: ["Source locator: card-1, Target locator: done-lane", "Destination position: Percent inside target, X percent: 82, Y percent: 50"],
    commonMistakes: ["Source và target phải là hai element đúng vai trò, ví dụ thumb cần kéo và track/vùng thả.", "Slider thường cần Percent inside target thay vì Center of target."],
  },
  type_sequence: {
    title: "Trợ giúp Type Sequence",
    summary: "Gõ từng ký tự vào element giống thao tác bàn phím.",
    useWhen: ["Dùng cho autocomplete, command palette, rich text editor, hoặc field phụ thuộc key events."],
    fields: [
      { name: "XPath", description: xpathField.vi },
      { name: "Text", description: "Chuỗi ký tự cần gõ." },
      { name: "Delay ms", description: "Độ trễ giữa các ký tự." },
      { name: "Iframe XPath", description: iframeField.vi },
      { name: "Wait until", description: waitUntilField.vi },
      { name: "Timeout ms", description: timeoutField.vi },
    ],
    examples: ["XPath: //*[@role='combobox'], Text: apple, Delay ms: 25"],
    commonMistakes: ["Dùng Fill Field cho field thường sẽ nhanh và ổn định hơn.", "Delay 0 không hợp lệ; bỏ trống nếu không cần delay."],
  },
  set_clipboard: {
    title: "Trợ giúp Set Clipboard",
    summary: "Đặt nội dung clipboard nội bộ của workflow để dùng ở step Paste Into Field.",
    useWhen: ["Dùng khi website xử lý dán tốt hơn gõ phím.", "Dùng trước Paste Into Field."],
    fields: [{ name: "Text", description: "Nội dung cần đưa vào clipboard workflow." }],
    examples: ["Text: Nội dung cần dán"],
    commonMistakes: ["Step này chỉ chuẩn bị nội dung; dùng Paste Into Field để dán vào field."],
  },
  read_text_file: {
    title: "Trợ giúp Đọc File Text",
    summary: "Đọc nội dung của file text cục bộ vào một biến của workflow.",
    useWhen: ["Dùng khi cần tải danh sách tài khoản, tham số cấu hình từ file cục bộ."],
    fields: [
      { name: "Path", description: "Đường dẫn file, có thể tuyệt đối hoặc tương đối so với workspace." },
      { name: "Encoding", description: "Định dạng mã hóa ký tự (ví dụ: utf-8, base64)." },
      { name: "Output name", description: "Tên biến dùng để lưu nội dung file đọc được." },
    ],
    examples: ["Path: inputs.txt, Encoding: utf-8, Output name: file_content"],
    commonMistakes: ["Đảm bảo đường dẫn file chính xác và file tồn tại trước khi chạy."],
  },
  parse_csv_excel: {
    title: "Trợ giúp Phân Tích CSV/Excel",
    summary: "Phân tích file CSV và lưu danh sách bản ghi dưới dạng mảng các object/array.",
    useWhen: ["Dùng khi bạn có danh sách dữ liệu đầu vào lớn lưu trong bảng tính CSV."],
    fields: [
      { name: "Path", description: "Đường dẫn file CSV cục bộ." },
      { name: "Delimiter", description: "Ký tự phân cách cột, mặc định là dấu phẩy (,)." },
      { name: "Has headers", description: "Sử dụng dòng đầu tiên làm tiêu đề cột (tên thuộc tính)." },
      { name: "Output name", description: "Tên biến dùng để lưu mảng dữ liệu phân tích được." },
    ],
    examples: ["Path: accounts.csv, Has headers: true, Output name: accounts_list"],
    commonMistakes: ["Đảm bảo file ở định dạng CSV hợp lệ. File Excel (.xlsx) cần xuất ra CSV trước."],
  },
  write_csv_excel: {
    title: "Trợ giúp Ghi CSV/Excel",
    summary: "Ghi hoặc chèn thêm mảng các object/array vào file CSV.",
    useWhen: ["Dùng để xuất kết quả cào được hoặc lưu nhật ký dữ liệu."],
    fields: [
      { name: "Path", description: "Đường dẫn file CSV đầu ra." },
      { name: "Source name", description: "Tên biến mảng chứa dữ liệu cần ghi." },
      { name: "Mode", description: "Chế độ ghi: ghi đè (overwrite) hoặc ghi nối tiếp (append)." },
      { name: "Has headers", description: "Ghi thêm tiêu đề cột vào file CSV." },
    ],
    examples: ["Path: results.csv, Source name: scraped_data, Mode: append"],
    commonMistakes: ["Biến nguồn phải là một mảng các object hoặc mảng các giá trị hợp lệ."],
  },
  file_operation: {
    title: "Trợ giúp Thao Tác File",
    summary: "Thực hiện các thao tác hệ thống như kiểm tra tồn tại, đổi tên, di chuyển hoặc xóa file.",
    useWhen: ["Dùng để dọn dẹp file tạm, tổ chức các file tải về."],
    fields: [
      { name: "Operation", description: "Thao tác: tồn tại (exists), xóa (delete), đổi tên (rename) hoặc di chuyển (move)." },
      { name: "Path", description: "Đường dẫn file hoặc thư mục nguồn." },
      { name: "Target path", description: "Đường dẫn đích (bắt buộc cho thao tác rename/move)." },
      { name: "Output name", description: "Tên biến tùy chọn để lưu kết quả thao tác." },
    ],
    examples: ["Operation: exists, Path: output.pdf, Output name: file_exists"],
    commonMistakes: ["Đảm bảo có quyền ghi trên thư mục đích khi rename/move file."],
  },
  http_request: {
    title: "Trợ giúp Yêu Cầu HTTP",
    summary: "Gửi yêu cầu HTTP (GET, POST, PUT, DELETE) đến API hoặc dịch vụ bên ngoài.",
    useWhen: ["Dùng để gọi API cấu hình, gửi webhook thông báo hoặc đẩy dữ liệu cào về server."],
    fields: [
      { name: "Method", description: "Phương thức HTTP (GET, POST, PUT, DELETE, PATCH)." },
      { name: "URL", description: "Đường dẫn URL đích." },
      { name: "Headers", description: "Các header cấu hình dưới dạng Name: Value (mỗi dòng một cặp)." },
      { name: "Body", description: "Nội dung body của request." },
      { name: "Content type", description: "Lựa chọn nhanh Content-Type cho header." },
      { name: "Timeout ms", description: "Thời gian chờ tối đa trước khi hủy request." },
      { name: "Output name", description: "Tên biến dùng để lưu kết quả trả về (status, headers, body)." },
    ],
    examples: ["Method: GET, URL: https://api.ipify.org?format=json, Output name: ip_info"],
    commonMistakes: ["Cần đảm bảo body là chuỗi JSON hợp lệ nếu gửi Content-Type là application/json."],
  },
  date_time_operation: {
    title: "Trợ giúp Thao Tác Date-Time",
    summary: "Tạo, định dạng, điều chỉnh hoặc so sánh ngày giờ.",
    useWhen: ["Dùng để tạo tên thư mục chứa timestamp, định dạng ngày đầu vào hoặc tính toán thời gian chạy."],
    fields: [
      { name: "Operation", description: "Thao tác: current_timestamp, format, add_subtract hoặc diff." },
      { name: "Value", description: "Giá trị ngày cơ sở (mặc định là hiện tại)." },
      { name: "Format pattern", description: "Định dạng đầu ra hoặc ngày thứ hai để tính khoảng cách (diff)." },
      { name: "Offset value", description: "Giá trị cần cộng hoặc trừ." },
      { name: "Offset unit", description: "Đơn vị: ngày (days), giờ (hours) hoặc phút (minutes)." },
      { name: "Output name", description: "Tên biến để lưu kết quả." },
    ],
    examples: ["Operation: format, Format pattern: YYYY-MM-DD, Output name: today_date"],
    commonMistakes: ["Ký tự định dạng phân biệt hoa thường (YYYY, MM, DD, HH, mm, ss)."],
  },
  crypto_operation: {
    title: "Trợ giúp Thao Tác Crypto",
    summary: "Tạo mã băm bảo mật (MD5, SHA-256) hoặc mã hóa/giải mã chuỗi dạng Base64.",
    useWhen: ["Dùng để băm mật khẩu, tạo chữ ký dữ liệu hoặc giải mã dữ liệu webhook."],
    fields: [
      { name: "Operation", description: "Thao tác: md5, sha256, base64_encode hoặc base64_decode." },
      { name: "Value", description: "Giá trị đầu vào cần xử lý." },
      { name: "Output name", description: "Tên biến lưu kết quả sau khi xử lý." },
    ],
    examples: ["Operation: sha256, Value: secret_pass, Output name: hashed_pass"],
    commonMistakes: ["Giải mã Base64 yêu cầu chuỗi nguồn phải ở định dạng Base64 hợp lệ."],
  },
  switch_frame: {
    title: "Trợ giúp Switch Frame",
    summary: "Chuyển ngữ cảnh trang vào bên trong một iframe.",
    useWhen: ["Dùng trước khi tương tác với các input hoặc nút bấm nằm trong iframe của bên thứ ba."],
    fields: [
      { name: "Iframe XPath", description: "XPath định vị thẻ iframe." },
    ],
    examples: ["Iframe XPath: //iframe[@id='payment']"],
    commonMistakes: ["Đảm bảo iframe đã được tải đầy đủ trước khi chuyển ngữ cảnh."],
  },
  switch_to_parent_frame: {
    title: "Trợ giúp Switch to Parent Frame",
    summary: "Quay lại ngữ cảnh trang chính (top-level document).",
    useWhen: ["Dùng sau khi đã hoàn thành tương tác trong iframe và muốn tiếp tục tương tác ở trang chính."],
    fields: [
      { name: "No fields", description: "Thao tác này không yêu cầu trường cấu hình nào." },
    ],
    examples: [],
    commonMistakes: ["Chỉ cần chuyển về parent frame nếu bạn cần tương tác với các thẻ HTML ngoài iframe hiện tại."],
  },
};
