import type { StepHelpContent } from "./stepHelpTypes";
import {
  elementHelpEn,
  variableHelpEn,
  xpathField,
  iframeField,
  waitUntilField,
  timeoutField,
  scrollTimeoutField,
} from "./stepHelpContentHelpers";

export const englishStepHelpContent: Record<string, StepHelpContent> = {
  navigate: {
    title: "Navigate Help",
    summary: "Open a URL and wait for the page using the selected load condition.",
    useWhen: ["Use at the start of a workflow to open the page you want to automate.", "Use when direct navigation is more reliable than clicking through."],
    fields: [
      { name: "URL", description: "The full page address, usually starting with https:// or http://." },
      { name: "Wait until", description: "Load waits for normal loading; DOMContentLoaded waits for HTML; Network idle waits for network activity to quiet down." },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["URL: https://example.com/login", "Wait until: Load, Timeout ms: 30000"],
    commonMistakes: ["Missing https:// at the start of the URL.", "Network idle can wait too long on pages that keep background requests open."],
  },
  wait: {
    title: "Wait Help",
    summary: "Wait for a condition before running the next step.",
    useWhen: ["Use when you know what must happen before the next step runs.", "Use to wait for elements, text, URL changes, or page load."],
    fields: [
      { name: "Condition", description: "The condition to wait for: time, element state, text, URL, or page load." },
      { name: "Duration ms", description: "Milliseconds to wait when Condition is Duration." },
      { name: "XPath", description: "XPath of the element to check when Condition is element_*." },
      { name: "Text", description: "Text that must appear when Condition is Text visible." },
      { name: "URL contains", description: "URL fragment that must appear when Condition is URL contains." },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["Condition: Element visible, XPath: //*[@id='result']", "Condition: URL contains, URL contains: /dashboard"],
    commonMistakes: ["Using fixed Duration when Wait element visible would be more stable.", "XPath must point to the element being checked."],
  },
  random_wait: {
    title: "Random Wait Help",
    summary: "Wait for a random duration inside a configured min/max range before running the next step.",
    useWhen: ["Use when a workflow needs a less mechanical rhythm between actions.", "Use instead of a fixed duration wait when each run should vary the pause."],
    fields: [
      { name: "Minimum wait ms", description: "The shortest allowed pause, in milliseconds." },
      { name: "Maximum wait ms", description: "The longest allowed pause, in milliseconds; must be greater than or equal to Minimum wait ms." },
    ],
    examples: ["Minimum wait ms: 500, Maximum wait ms: 1500"],
    commonMistakes: ["Setting the maximum lower than the minimum.", "Using random wait to mask a timing bug when a condition-based Wait would be more reliable."],
  },
  input_text: {
    title: "Fill Field Help",
    summary: "Enter text into an input, textarea, or editable element.",
    useWhen: ["Use for login forms, search boxes, textareas, or fields that need text.", "Use when you need iframe support, advanced waiting, or more user-like typing."],
    fields: [
      { name: "XPath", description: xpathField.en },
      { name: "Text", description: "The text to enter into the field." },
      { name: "Clear before input", description: "Yes clears the old value before entering text." },
      { name: "Typing mode", description: "Set value is fast; Type keys behaves more like real keyboard input." },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Delay ms", description: "Delay between keystrokes when using Type keys." },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["XPath: //*[@name='email']", "Iframe XPath: //*[@id='login-frame'], XPath: //*[@name='email']"],
    commonMistakes: ["XPath points to a label or wrapper div instead of the real input.", "Elements inside iframes need Iframe XPath too."],
  },
  clear_input: {
    title: "Clear Input Help",
    summary: "Clear the value from an input field.",
    useWhen: ["Use before entering new text when the field already has a value.", "Use to reset a search box or textarea."],
    fields: [
      { name: "XPath", description: xpathField.en },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
      { name: "Method", description: "Select all uses Ctrl/Cmd+A; Backspace deletes with keys; DOM value directly sets an empty value." },
    ],
    examples: ["XPath: //*[@name='email'], Method: Select all"],
    commonMistakes: ["XPath must point to an editable field, not visible text."],
  },
  click: {
    title: "Click Help",
    summary: "Click an element such as a button, link, custom checkbox, or menu.",
    useWhen: ["Use to press Submit, open dropdowns, select tabs, or click links.", "Use Real click when you want browser-like user behavior."],
    fields: [
      { name: "Target source", description: "Use locator shows direct locator fields; Use Find Element ref uses only Target ref from a previous Find Element node." },
      { name: "Target ref", description: "Find Element output name, for example current_like. When Target ref is set, the action ignores locator fields." },
      { name: "XPath", description: xpathField.en },
      { name: "Mode", description: "Real click uses browser mouse events; Force DOM click calls click() directly when mouse interaction is difficult." },
      { name: "Click count", description: "Single click or double click." },
      { name: "Button", description: "Left, right, or middle mouse button." },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Scroll into view", description: "Yes brings the element into view before clicking." },
      { name: "Block / Inline", description: "Controls alignment when scrolling into view." },
      { name: "Position", description: "Where to click on the element. Offset lets you enter X/Y coordinates." },
      { name: "Offset X / Offset Y", description: "Click coordinates from the element's top-left corner when Position is Offset." },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["Target source: Use locator, XPath: //*[@type='submit']", "Target source: Use Find Element ref, Target ref: current_like"],
    commonMistakes: ["XPath points to text inside a button instead of the clickable button.", "When Target ref is selected, locator visibility/contains/index fields no longer apply."],
  },
  find_element: {
    title: "Find Element Help",
    summary: "Resolve a matching element, filter/rank it by viewport, and store a short-lived ref for a later step such as Click.",
    useWhen: ["Use when many similar buttons exist in the DOM but you need the one currently in view.", "Use before Click with Target ref to separate element selection from clicking."],
    fields: [
      { name: "Target locator", description: "The real locator for candidate elements, such as all Like buttons inside articles." },
      { name: "Output name", description: "Runtime ref name that the next step can use through Target ref." },
      { name: "In viewport", description: "Required only selects elements intersecting the current viewport." },
      { name: "Rank", description: "Nearest viewport center chooses the candidate closest to screen center; Largest visible area chooses the most exposed candidate." },
    ],
    examples: ["Target locator: article button[aria-label^='Like video'][aria-pressed='false']", "Output name: current_like, Rank: Nearest viewport center"],
    commonMistakes: ["Using Target index instead of Rank can click the wrong post on scrolling or virtualized feeds.", "Turning In viewport off returns to first-DOM-match behavior."],
  },
  scroll: {
    title: "Scroll Help",
    summary: "Scroll the page by pixels, bring an existing element into view, or scroll to find a lazy-loaded element.",
    useWhen: ["Use Page Scroll for a fixed pixel-distance scroll.", "Use Scroll To Element when the element is already on the page but outside the viewport.", "Use Scroll Until Element Visible when page scrolling must trigger lazy-load DOM mounting."],
    fields: [
      { name: "Mode", description: "Page Scroll and target modes use gestures made of smaller wheel pulses, short pauses inside each gesture, and longer random pauses between gestures." },
      { name: "Scroll style", description: "Human-like splits Page Scroll into several pulses and pauses; Smooth single wheel sends one wheel gesture for the exact pixel distance." },
      { name: "Direction", description: "Page Scroll direction or Scroll Until Element Visible search direction: down, up, right, or left." },
      { name: "Pixels", description: "Pixel distance for Page Scroll or each search scroll. Try 250-800 depending on the page." },
      { name: "Target locator", description: "Target element for Scroll To Element or Scroll Until Element Visible." },
      { name: "Iframe XPath", description: "Selects the parent-page iframe when the target uses a legacy XPath inside a frame." },
      { name: "Timeout ms", description: scrollTimeoutField.en },
    ],
    examples: ["Mode: Page Scroll, Direction: Down, Pixels: 500", "Mode: Scroll To Element, Iframe XPath: //*[@id='main-frame'], Target locator: //h2[normalize-space(.)='Ready']", "Mode: Scroll Until Element Visible, Direction: Down, Pixels: 700, Target locator: lazy card"],
    commonMistakes: ["If the element is inside an iframe, set Iframe XPath for the iframe and the target locator inside that iframe.", "Scroll To Element needs the target to already exist in the DOM; use Scroll Until Element Visible for lazy-load pages.", "Target scroll calculates human-like chunks and pauses automatically."],
  },
  select_option: {
    title: "Select Option Help",
    summary: "Select an option from a native HTML select dropdown.",
    useWhen: ["Use for native dropdowns such as country, category, or status.", "Do not use for custom div dropdowns; those usually need Click steps."],
    fields: [
      { name: "XPath", description: "XPath of the select element, not the option." },
      { name: "Match by", description: "Label matches visible text; Value matches the option value attribute." },
      { name: "Value", description: "The label or value to select, depending on Match by." },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["XPath: //*[@name='country'], Match by: Label, Value: Vietnam"],
    commonMistakes: ["XPath points to an option instead of the select.", "Custom dropdowns that are not select elements need a different step."],
  },
  press_key: {
    title: "Press Key Help",
    summary: "Press one keyboard key.",
    useWhen: ["Use for Enter, Tab, Escape, or ArrowDown after another step.", "Use when the website reacts to keyboard input instead of clicks."],
    fields: [{ name: "Key", description: "The key name to press, for example Enter, Tab, Escape, ArrowDown." }],
    examples: ["Key: Enter", "Key: Escape"],
    commonMistakes: ["This presses one key; combinations like Control+S should use Hotkey."],
  },
  hotkey: {
    title: "Hotkey Help",
    summary: "Press a keyboard shortcut.",
    useWhen: ["Use for Ctrl+S, Ctrl+A, Cmd+K, Alt+Enter.", "Use when the web app has keyboard shortcuts."],
    fields: [{ name: "Keys", description: "Enter keys separated by +, for example Control+S or Meta+K." }],
    examples: ["Keys: Control+S", "Keys: Meta+K"],
    commonMistakes: ["On macOS, Command is usually Meta.", "Avoid unnecessary extra spaces."],
  },
  hover: {
    title: "Hover Help",
    summary: "Move the mouse over an element.",
    useWhen: ["Use to open hover menus, tooltips, or reveal hidden buttons.", "Use before Click when a button only appears after hover."],
    fields: [
      { name: "XPath", description: xpathField.en },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["XPath: //*[@aria-label='User menu']"],
    commonMistakes: ["Hover only moves the mouse; it does not click.", "If a menu opens by click, use Click instead of Hover."],
  },
  get_current_url: {
    title: "Get Current URL Help",
    summary: "Capture the current page URL and store it in system.current_url.",
    useWhen: ["Use when you need the current URL, query params, or path segments."],
    fields: [
      { name: "Output", description: "URL data is stored in system.current_url with fields: href, origin, protocol, hostname, port, pathname, search, hash, params, segments, base." },
    ],
    examples: [],
    commonMistakes: ["Make sure the page has finished navigating before capturing the URL."],
  },
};

export const phaseOneEnglishStepHelpContent: Record<string, StepHelpContent> = {
  double_click: elementHelpEn("Double Click", "double click", "double-click"),
  right_click: elementHelpEn("Right Click", "right click", "context menu"),
  focus_element: elementHelpEn("Focus Element", "focus", "keyboard input"),
  blur_element: elementHelpEn("Blur Element", "blur", "validation"),
  paste_clipboard: elementHelpEn("Paste Into Field", "paste clipboard text into a field", "paste"),
  check: elementHelpEn("Check", "ensure a checkbox is checked", "checkbox"),
  uncheck: elementHelpEn("Uncheck", "ensure a checkbox is unchecked", "checkbox"),
  toggle_checkbox: elementHelpEn("Toggle Checkbox", "toggle a checkbox", "checkbox"),
  select_radio: elementHelpEn("Select Radio", "select a radio option", "radio"),
  upload_file: elementHelpEn("Upload File", "upload local files", "file"),
  submit_form: elementHelpEn("Submit Form", "submit a form", "submit"),
  select_custom_option: elementHelpEn("Select Custom Option", "select a custom dropdown option", "combobox"),
  set_contenteditable: elementHelpEn("Set Contenteditable", "set rich text content", "editor"),
  extract_text: elementHelpEn("Extract Text", "capture visible text", "output"),
  extract_attribute: elementHelpEn("Extract Attribute", "capture an element attribute", "output"),
  extract_input_value: elementHelpEn("Extract Input Value", "capture an input value", "output"),
  extract_table: elementHelpEn("Extract Table", "capture table rows", "output"),
  extract_list: elementHelpEn("Extract List", "capture list items", "output"),
  count_elements: elementHelpEn("Count Elements", "count matching elements", "output"),
  extract_regex_matches: {
    title: "Extract Regex Matches Help",
    summary: "Read an existing output, collect regex matches, and save the matches into a new or existing output.",
    useWhen: ["Use after Extract Text or Extract List when you need URLs, usernames, order ids, or tokens from captured text."],
    fields: [
      { name: "Source output", description: "Input output name to read, such as post_text or comment_text." },
      { name: "Pattern", description: "Regex pattern used to find matches in the source output." },
      { name: "Flags", description: "Regex flags such as g, i, m; g is used so multiple matches can be collected." },
      { name: "Output name", description: "Output name that stores the match list." },
      { name: "Append", description: "Enable to add matches to an existing output list instead of replacing it." },
      { name: "Dedupe", description: "Enable to keep each matched value once in the output list." },
    ],
    examples: ["Source output: comment_text, Pattern: @[A-Za-z0-9._-]+, Output name: tiktok_targets"],
    commonMistakes: ["Invalid regex syntax fails validation.", "Turning Append off inside a loop keeps only the last loop result."],
  },
  go_back: elementHelpEn("Go Back", "go back in browser history", "history"),
  go_forward: elementHelpEn("Go Forward", "go forward in browser history", "history"),
  reload: elementHelpEn("Reload", "reload the current tab", "browser"),
  open_new_tab: elementHelpEn("Open New Tab", "open a new browser tab", "tab"),
  click_and_switch_tab: elementHelpEn("Click & Switch Tab", "click and switch to a new tab", "open-tab"),
  switch_tab: elementHelpEn("Switch Tab", "switch to a different browser tab", "tab"),
  close_tab: elementHelpEn("Close Tab", "close a browser tab", "tab"),
  accept_dialog: elementHelpEn("Accept Dialog", "accept an alert, confirm, or prompt", "dialog"),
  dismiss_dialog: elementHelpEn("Dismiss Dialog", "dismiss an alert, confirm, or prompt", "dialog"),
  wait_for_download: elementHelpEn("Wait For Download", "wait until a new downloaded file exists", "download"),
  write_text_file: {
    title: "Write Text File Help",
    summary: "Write an output as a text file inside the run evidence directory and store the artifact path in an output.",
    useWhen: ["Use at the end of a workflow to export captured URLs, usernames, short logs, or collected data."],
    fields: [
      { name: "Source output", description: "Output name to write into the file." },
      { name: "Path", description: "Safe artifact file name, for example tiktok-usernames.txt." },
      { name: "Separator", description: "String used between array items; use \\n for one item per line." },
      { name: "Trailing newline", description: "Enable to append a final newline to the file." },
      { name: "Output name", description: "Output name that stores the evidence-relative file path." },
    ],
    examples: ["Source output: tiktok_targets, Path: tiktok-usernames.txt, Output name: tiktok_username_file"],
    commonMistakes: ["Path is only an artifact file name, not a filesystem path.", "An empty source output creates an empty file."],
  },
  set_variable: elementHelpEn("Set Variables", "save reusable values", "variable"),
  set_json_variables: elementHelpEn("Set JSON Variables", "save structured JSON values", "variable"),
  update_number_variable: variableHelpEn("Update Number Variable", "perform math operations on a number variable"),
  set_number_variable: {
    title: "Set Number Variable Help",
    summary: "Directly assign a numeric value to a variable.",
    useWhen: ["Use to initialize count variables or store specific numbers."],
    fields: [
      { name: "Result variable", description: "The variable name to store the number in." },
      { name: "Value", description: "The number value to assign (supports variable templates like {{variable}})." },
    ],
    examples: ["Result variable: item_count, Value: 10"],
    commonMistakes: ["Entering non-numeric text values that fail to parse as a number."],
  },
  generate_random_number: {
    title: "Generate Random Number Help",
    summary: "Generate a random decimal or integer within a specified range.",
    useWhen: ["Use to simulate varying delays or create random index variables."],
    fields: [
      { name: "Result variable", description: "The variable name to store the generated random number." },
      { name: "Minimum value", description: "The lower bound of the random range." },
      { name: "Maximum value", description: "The upper bound of the random range." },
      { name: "Generate integer only", description: "Enable to generate whole numbers; disable for float/decimals." },
    ],
    examples: ["Result variable: rand_delay, Minimum value: 5, Maximum value: 15, Generate integer only: Yes"],
    commonMistakes: ["Setting the minimum bound greater than the maximum bound."],
  },
  parse_text_to_number: {
    title: "Parse Text to Number Help",
    summary: "Convert a text string into a numeric value, with an optional fallback if parsing fails.",
    useWhen: ["Use after extracting price or quantity strings from a web page to convert them to numbers for math."],
    fields: [
      { name: "Source text", description: "The string to parse." },
      { name: "Fallback value", description: "Fallback value if parsing fails." },
      { name: "Result variable", description: "The variable name to store the parsed number." },
    ],
    examples: ["Source text: {{outputs.price_text}}, Fallback value: 0, Result variable: parsed_price"],
    commonMistakes: ["The source text contains currency symbols (e.g. $) or commas that should be stripped first."],
  },
  math_operation: {
    title: "Math Operation Help",
    summary: "Perform basic arithmetic (add, subtract, multiply, divide, modulo, power) or unary math operations (abs, sqrt, min, max).",
    useWhen: ["Use to increment counters, add values together, find minimums, or calculate square roots."],
    fields: [
      { name: "Operand 1", description: "First operand (number or variable)." },
      { name: "Operation", description: "The mathematical operation to execute." },
      { name: "Operand 2", description: "Second operand (ignored for unary operations like abs and sqrt)." },
      { name: "Result variable", description: "The variable name to store the result." },
    ],
    examples: ["Operand 1: {{outputs.counter}}, Operation: Add, Operand 2: 1, Result variable: counter"],
    commonMistakes: ["Dividing by zero in division operations."],
  },
  round_number: {
    title: "Round Number Help",
    summary: "Round a number using round (nearest), floor (down), or ceil (up) to a specified decimal precision.",
    useWhen: ["Use to clean up division results or format decimals to a fixed precision."],
    fields: [
      { name: "Source number", description: "The number to round." },
      { name: "Rounding mode", description: "The rounding strategy to use." },
      { name: "Decimal places", description: "Number of decimal places to keep." },
      { name: "Result variable", description: "The variable name to store the rounded number." },
    ],
    examples: ["Source number: {{outputs.math_result}}, Rounding mode: Round, Decimal places: 2"],
    commonMistakes: ["Specifying a negative decimal precision."],
  },
  format_number: {
    title: "Format Number Help",
    summary: "Format a number into a formatted text string (decimal, percent, or currency) based on locale rules.",
    useWhen: ["Use when preparing numeric output for reports, tables, or export files."],
    fields: [
      { name: "Source number", description: "The number to format." },
      { name: "Format style", description: "The style: decimal, percent, or currency." },
      { name: "Decimal places", description: "Number of decimal digits." },
      { name: "Currency code", description: "International currency code (e.g., USD, EUR) if style is currency." },
      { name: "Locale", description: "The locale identifier (e.g., en-US, vi-VN)." },
      { name: "Result variable", description: "The variable name to store the formatted text string." },
    ],
    examples: ["Source number: 1234.5, Format style: Currency, Currency code: USD, Locale: en-US"],
    commonMistakes: ["Using invalid locale codes or currency codes that crash the formatting runtime."],
  },
  compare_numbers: {
    title: "Compare Numbers Help",
    summary: "Compare two numbers and return a boolean result (true or false).",
    useWhen: ["Use for conditional branching in If conditions or while loop steps."],
    fields: [
      { name: "Operand 1", description: "First number/variable." },
      { name: "Comparison operator", description: "The comparison operator (gt, gte, lt, lte, eq, neq)." },
      { name: "Operand 2", description: "Second number/variable." },
      { name: "Result variable", description: "The variable name to store the boolean comparison result." },
    ],
    examples: ["Operand 1: {{outputs.price}}, Comparison operator: gt, Operand 2: 100, Result variable: is_expensive"],
    commonMistakes: ["Comparing numeric variables with unparsed string values."],
  },
  check_number_range: {
    title: "Check Number Range Help",
    summary: "Verify if a number lies within a specified min/max range.",
    useWhen: ["Use to validate number boundaries or filter out-of-bounds results."],
    fields: [
      { name: "Number value", description: "The number to check." },
      { name: "Minimum bound", description: "The lower bound value." },
      { name: "Maximum bound", description: "The upper bound value." },
      { name: "Inclusive bounds", description: "Enable to include the boundaries (min <= value <= max)." },
      { name: "Result variable", description: "The variable name to store the true/false result." },
    ],
    examples: ["Number value: {{outputs.age}}, Minimum bound: 18, Maximum bound: 60, Result variable: is_working_age"],
    commonMistakes: ["Setting the lower bound higher than the upper bound."],
  },
  check_number_property: {
    title: "Check Number Property Help",
    summary: "Test a number value for mathematical properties (even, odd, integer, positive, negative).",
    useWhen: ["Use to check index variables or test if a computed value is negative before math."],
    fields: [
      { name: "Number value", description: "The number to check." },
      { name: "Property to check", description: "The property to test (even, odd, integer, positive, negative)." },
      { name: "Result variable", description: "The variable name to store the true/false result." },
    ],
    examples: ["Number value: {{outputs.item_index}}, Property to check: Even, Result variable: is_even_row"],
    commonMistakes: ["Checking even/odd properties on float/decimal values."],
  },
  update_text_variable: variableHelpEn("Update Text Variable", "perform string operations on a text variable"),
  set_boolean_variable: variableHelpEn("Boolean: Set Value", "assign a boolean value directly"),
  generate_random_boolean: variableHelpEn("Boolean: Random", "generate a random boolean"),
  parse_to_boolean: variableHelpEn("Boolean: Convert Value", "convert text/number value to boolean"),
  boolean_logical_op: variableHelpEn("Boolean: Logical Op", "perform logical operations on booleans"),
  compare_booleans: variableHelpEn("Boolean: Compare", "compare two boolean values"),
  check_boolean_property: variableHelpEn("Boolean: Check Property", "check boolean variable property"),
  update_flag_variable: variableHelpEn("Update Flag Variable", "update boolean flag variable"),
  update_list_variable: variableHelpEn("Update List Variable", "perform array operations on a list variable"),
  assert_element: elementHelpEn("Assert Element", "require an element state", "assert"),
  assert_text: elementHelpEn("Assert Text", "require expected text", "assert"),
  graph_noop: elementHelpEn("Graph No-op", "mark internal graph flow progress", "logic"),
  if_condition: elementHelpEn("If Condition", "run steps when a condition matches", "logic"),
  router_condition: elementHelpEn("Router Condition", "run first matching router case", "logic"),
  random_choice: elementHelpEn("Random Choice", "choose one weighted branch", "logic"),
  repeat_times: elementHelpEn("Repeat Times", "repeat nested steps", "loop"),
  repeat_for_each: elementHelpEn("Repeat For Each", "repeat steps for each item", "loop"),
  retry_block: elementHelpEn("Retry Block", "retry nested steps after failure", "retry"),
  stop_workflow: elementHelpEn("Stop Workflow", "stop the workflow intentionally", "stop"),
  set_cookie: elementHelpEn("Set Cookie", "set a visible browser cookie", "cookie"),
  clear_cookies: elementHelpEn("Clear Cookies", "clear visible browser cookies", "cookie"),
  set_viewport: elementHelpEn("Set Viewport", "set runtime viewport size", "device"),
  set_geolocation: elementHelpEn("Set Geolocation", "override browser geolocation", "geo"),
  set_extra_headers: elementHelpEn("Set Extra Headers", "send extra HTTP headers", "headers"),
  grant_permission: elementHelpEn("Grant Permission", "grant browser permissions", "permission"),
  execute_js: elementHelpEn("Execute JS", "run advanced JavaScript", "advanced"),
  wait_for_request: elementHelpEn("Wait For Request", "wait for a network request", "network"),
  wait_for_response: elementHelpEn("Wait For Response", "wait for a network response", "network"),
  block_request: elementHelpEn("Block Request", "block matching fetch requests", "network"),
  mock_response: elementHelpEn("Mock Response", "mock a matching fetch response", "network"),
  set_local_storage: elementHelpEn("Set Local Storage", "set localStorage", "storage"),
  set_session_storage: elementHelpEn("Set Session Storage", "set sessionStorage", "storage"),
  take_screenshot: {
    title: "Take Screenshot Help",
    summary: "Capture the current page and save the path into outputs when Output name is set.",
    useWhen: ["Use to keep visual evidence after an important workflow action."],
    fields: [
      { name: "Path", description: "PNG file path to write." },
      { name: "Output name", description: "Output variable name that stores the screenshot path." },
      { name: "Full page", description: "Yes captures the full page; No captures the current viewport." },
    ],
    examples: ["Path: /tmp/workflow-result.png, Output name: screenshot_path"],
    commonMistakes: ["The parent folder of Path must exist.", "An existing file at the same path is overwritten."],
  },
  drag_and_drop: {
    title: "Drag and Drop Help",
    summary: "Drag a source element and drop it onto a target element.",
    useWhen: ["Use for reordering cards, moving items into drop zones, or kanban-style UIs."],
    fields: [
      { name: "Source selection", description: "Choose a direct locator or Find Element ref for the element to drag." },
      { name: "Source ref", description: "Find Element output name when Drag source uses a runtime ref." },
      { name: "Source locator", description: "Locator for the element to drag." },
      { name: "Drop target source", description: "Choose a direct locator or Find Element ref for the destination element or area." },
      { name: "Drop target ref", description: "Find Element output name when Drop target uses a runtime ref." },
      { name: "Target locator", description: "Locator for the drop target element or area." },
      { name: "Destination position", description: "Drop point inside the target: target center, percent inside the target, or pixel offset from the target's top-left corner." },
      { name: "X percent", description: "Horizontal coordinate inside the target when Destination position is Percent inside target." },
      { name: "Y percent", description: "Vertical coordinate inside the target when Destination position is Percent inside target." },
      { name: "X offset px", description: "Horizontal pixels from the target's top-left corner when using Pixel offset." },
      { name: "Y offset px", description: "Vertical pixels from the target's top-left corner when using Pixel offset." },
    ],
    examples: ["Source locator: card-1, Target locator: done-lane", "Destination position: Percent inside target, X percent: 82, Y percent: 50"],
    commonMistakes: ["Source and target should be the right elements for their roles, such as the draggable thumb and the track/drop zone.", "Sliders usually need Percent inside target instead of Center of target."],
  },
  type_sequence: {
    title: "Type Sequence Help",
    summary: "Type text character by character with keyboard-like events.",
    useWhen: ["Use for autocomplete, command palettes, rich text editors, or fields that depend on key events."],
    fields: [
      { name: "XPath", description: xpathField.en },
      { name: "Text", description: "The characters to type." },
      { name: "Delay ms", description: "Delay between characters." },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["XPath: //*[@role='combobox'], Text: apple, Delay ms: 25"],
    commonMistakes: ["Fill Field is faster and more stable for normal fields.", "Delay 0 is invalid; leave it blank when no delay is needed."],
  },
  set_clipboard: {
    title: "Set Clipboard Help",
    summary: "Set the workflow clipboard text for a later Paste Into Field step.",
    useWhen: ["Use when the site handles paste better than typing.", "Use before Paste Into Field."],
    fields: [{ name: "Text", description: "The text to place into the workflow clipboard." }],
    examples: ["Text: Text to paste"],
    commonMistakes: ["This only prepares the text; use Paste Into Field to put it into a field."],
  },
  read_text_file: {
    title: "Read Text File Help",
    summary: "Read a local text file's contents into a workflow variable.",
    useWhen: ["Use when you need to load credentials, input parameters, or raw configuration from a local file."],
    fields: [
      { name: "Path", description: "File path, either absolute or relative to the workspace." },
      { name: "Encoding", description: "Character encoding to use (e.g. utf-8, base64)." },
      { name: "Output name", description: "Variable name to store the file content." },
    ],
    examples: ["Path: inputs.txt, Encoding: utf-8, Output name: file_content"],
    commonMistakes: ["Make sure the file path is accessible and the file exists."],
  },
  parse_csv_excel: {
    title: "Parse CSV/Excel Help",
    summary: "Parse a CSV file and store structured records as an array of objects or arrays.",
    useWhen: ["Use when you have bulk inputs or lists stored in a CSV spreadsheet."],
    fields: [
      { name: "Path", description: "CSV file path, either absolute or relative." },
      { name: "Delimiter", description: "Delimiter character, defaults to comma (,)." },
      { name: "Has headers", description: "Treat the first row as column headers (keys)." },
      { name: "Output name", description: "Variable name to store the parsed records array." },
    ],
    examples: ["Path: accounts.csv, Has headers: true, Output name: accounts_list"],
    commonMistakes: ["Ensure the file is a valid CSV. Excel files (.xlsx) must be saved as CSV first."],
  },
  write_csv_excel: {
    title: "Write CSV/Excel Help",
    summary: "Write or append an array of objects/arrays to a CSV file.",
    useWhen: ["Use to export scraped results or update a local CSV database."],
    fields: [
      { name: "Path", description: "Target CSV file path, either absolute or relative." },
      { name: "Source name", description: "Array variable name to read records from." },
      { name: "Mode", description: "Write mode: overwrite or append." },
      { name: "Has headers", description: "Include header columns in the CSV output." },
    ],
    examples: ["Path: results.csv, Source name: scraped_data, Mode: append"],
    commonMistakes: ["Source variable must be a valid array of objects or arrays."],
  },
  file_operation: {
    title: "File Operation Help",
    summary: "Perform filesystem operations like checking existence, renaming, moving, or deleting files.",
    useWhen: ["Use to clean up temporary files or organize downloaded assets."],
    fields: [
      { name: "Operation", description: "Operation: exists, delete, rename, or move." },
      { name: "Path", description: "Source file or directory path." },
      { name: "Target path", description: "Target path required for rename or move." },
      { name: "Output name", description: "Optional output variable to store operation results." },
    ],
    examples: ["Operation: exists, Path: output.pdf, Output name: file_exists"],
    commonMistakes: ["Verify permissions when renaming or deleting files outside the profile directory."],
  },
  http_request: {
    title: "HTTP Request Help",
    summary: "Send HTTP requests (GET, POST, PUT, DELETE) to external APIs or services.",
    useWhen: ["Use to fetch dynamic configs, trigger webhook notifications, or submit data directly to an API."],
    fields: [
      { name: "Method", description: "HTTP method (GET, POST, PUT, DELETE, PATCH)." },
      { name: "URL", description: "Request URL destination." },
      { name: "Headers", description: "Headers configured as Name: Value pairs, one per line." },
      { name: "Body", description: "JSON or raw request body text." },
      { name: "Content type", description: "Optional Content-Type header shortcut." },
      { name: "Timeout ms", description: "Abort request after this timeout." },
      { name: "Output name", description: "Variable name to store the response object (status, headers, body)." },
    ],
    examples: ["Method: GET, URL: https://api.ipify.org?format=json, Output name: ip_info"],
    commonMistakes: ["Make sure request body is valid JSON if Content-Type is application/json."],
  },
  date_time_operation: {
    title: "Date-Time Operation Help",
    summary: "Generate, format, adjust, or compare dates and timestamps.",
    useWhen: ["Use to generate unique folder names, format date inputs, or calculate runtime durations."],
    fields: [
      { name: "Operation", description: "Operation: current_timestamp, format, add_subtract, or diff." },
      { name: "Value", description: "Base date value (defaults to now)." },
      { name: "Format pattern", description: "Output format pattern or second date value for diff." },
      { name: "Offset value", description: "Value to add or subtract." },
      { name: "Offset unit", description: "Unit: days, hours, or minutes." },
      { name: "Output name", description: "Variable name to store the result." },
    ],
    examples: ["Operation: format, Format pattern: YYYY-MM-DD, Output name: today_date"],
    commonMistakes: ["Format pattern uses case-sensitive tokens (YYYY, MM, DD, HH, mm, ss)."],
  },
  crypto_operation: {
    title: "Crypto Operation Help",
    summary: "Generate cryptographic hashes (MD5, SHA-256) or encode/decode Base64 strings.",
    useWhen: ["Use to hash passwords, generate integrity signatures, or decode webhook data."],
    fields: [
      { name: "Operation", description: "Operation: md5, sha256, base64_encode, or base64_decode." },
      { name: "Value", description: "Value to process." },
      { name: "Output name", description: "Variable name to store the hashed/transferred result." },
    ],
    examples: ["Operation: sha256, Value: secret_pass, Output name: hashed_pass"],
    commonMistakes: ["Base64 decoding requires a valid Base64 encoded source string."],
  },
  switch_frame: {
    title: "Switch Frame Help",
    summary: "Switch the page frame context to a target iframe.",
    useWhen: ["Use before interacting with form fields or elements nested inside an iframe."],
    fields: [
      { name: "Iframe XPath", description: "XPath selector targeting the iframe element." },
    ],
    examples: ["Iframe XPath: //iframe[@id='payment']"],
    commonMistakes: ["Make sure the iframe is fully loaded before switching."],
  },
  switch_to_parent_frame: {
    title: "Switch to Parent Frame Help",
    summary: "Switch context back to the main/top-level page document.",
    useWhen: ["Use after finishing interactions inside an iframe to resume top-level page execution."],
    fields: [
      { name: "No fields", description: "This action does not have any fields." },
    ],
    examples: [],
    commonMistakes: ["Switching back is only necessary if you need to access elements outside the active iframe."],
  },
};
