import type { StepHelpContent } from "./stepHelpTypes";
import {
  elementHelpEn,
  variableHelpEn,
  xpathField,
  iframeField,
  waitUntilField,
  timeoutField,
  scrollTimeoutField,
} from "./stepHelpContentHelpers";

export const englishStepHelpContent: Record<string, StepHelpContent> = {
  navigate: {
    title: "Navigate Help",
    summary: "Open a URL and wait for the page using the selected load condition.",
    useWhen: ["Use at the start of a workflow to open the page you want to automate.", "Use when direct navigation is more reliable than clicking through."],
    fields: [
      { name: "URL", description: "The full page address, usually starting with https:// or http://." },
      { name: "Wait until", description: "Load waits for normal loading; DOMContentLoaded waits for HTML; Network idle waits for network activity to quiet down." },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["URL: https://example.com/login", "Wait until: Load, Timeout ms: 30000"],
    commonMistakes: ["Missing https:// at the start of the URL.", "Network idle can wait too long on pages that keep background requests open."],
  },
  wait: {
    title: "Wait Help",
    summary: "Wait for a condition before running the next step.",
    useWhen: ["Use when you know what must happen before the next step runs.", "Use to wait for elements, text, URL changes, or page load."],
    fields: [
      { name: "Condition", description: "The condition to wait for: time, element state, text, URL, or page load." },
      { name: "Duration ms", description: "Milliseconds to wait when Condition is Duration." },
      { name: "XPath", description: "XPath of the element to check when Condition is element_*." },
      { name: "Text", description: "Text that must appear when Condition is Text visible." },
      { name: "URL contains", description: "URL fragment that must appear when Condition is URL contains." },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["Condition: Element visible, XPath: //*[@id='result']", "Condition: URL contains, URL contains: /dashboard"],
    commonMistakes: ["Using fixed Duration when Wait element visible would be more stable.", "XPath must point to the element being checked."],
  },
  random_wait: {
    title: "Random Wait Help",
    summary: "Wait for a random duration inside a configured min/max range before running the next step.",
    useWhen: ["Use when a workflow needs a less mechanical rhythm between actions.", "Use instead of a fixed duration wait when each run should vary the pause."],
    fields: [
      { name: "Minimum wait ms", description: "The shortest allowed pause, in milliseconds." },
      { name: "Maximum wait ms", description: "The longest allowed pause, in milliseconds; must be greater than or equal to Minimum wait ms." },
    ],
    examples: ["Minimum wait ms: 500, Maximum wait ms: 1500"],
    commonMistakes: ["Setting the maximum lower than the minimum.", "Using random wait to mask a timing bug when a condition-based Wait would be more reliable."],
  },
  input_text: {
    title: "Fill Field Help",
    summary: "Enter text into an input, textarea, or editable element.",
    useWhen: ["Use for login forms, search boxes, textareas, or fields that need text.", "Use when you need iframe support, advanced waiting, or more user-like typing."],
    fields: [
      { name: "XPath", description: xpathField.en },
      { name: "Text", description: "The text to enter into the field." },
      { name: "Clear before input", description: "Yes clears the old value before entering text." },
      { name: "Typing mode", description: "Set value is fast; Type keys behaves more like real keyboard input." },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Delay ms", description: "Delay between keystrokes when using Type keys." },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["XPath: //*[@name='email']", "Iframe XPath: //*[@id='login-frame'], XPath: //*[@name='email']"],
    commonMistakes: ["XPath points to a label or wrapper div instead of the real input.", "Elements inside iframes need Iframe XPath too."],
  },
  clear_input: {
    title: "Clear Input Help",
    summary: "Clear the value from an input field.",
    useWhen: ["Use before entering new text when the field already has a value.", "Use to reset a search box or textarea."],
    fields: [
      { name: "XPath", description: xpathField.en },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
      { name: "Method", description: "Select all uses Ctrl/Cmd+A; Backspace deletes with keys; DOM value directly sets an empty value." },
    ],
    examples: ["XPath: //*[@name='email'], Method: Select all"],
    commonMistakes: ["XPath must point to an editable field, not visible text."],
  },
  click: {
    title: "Click Help",
    summary: "Click an element such as a button, link, custom checkbox, or menu.",
    useWhen: ["Use to press Submit, open dropdowns, select tabs, or click links.", "Use Real click when you want browser-like user behavior."],
    fields: [
      { name: "Target source", description: "Use locator shows direct locator fields; Use Find Element ref uses only Target ref from a previous Find Element node." },
      { name: "Target ref", description: "Find Element output name, for example current_like. When Target ref is set, the action ignores locator fields." },
      { name: "XPath", description: xpathField.en },
      { name: "Mode", description: "Real click uses browser mouse events; Force DOM click calls click() directly when mouse interaction is difficult." },
      { name: "Click count", description: "Single click or double click." },
      { name: "Button", description: "Left, right, or middle mouse button." },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Scroll into view", description: "Yes brings the element into view before clicking." },
      { name: "Block / Inline", description: "Controls alignment when scrolling into view." },
      { name: "Position", description: "Where to click on the element. Offset lets you enter X/Y coordinates." },
      { name: "Offset X / Offset Y", description: "Click coordinates from the element's top-left corner when Position is Offset." },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["Target source: Use locator, XPath: //*[@type='submit']", "Target source: Use Find Element ref, Target ref: current_like"],
    commonMistakes: ["XPath points to text inside a button instead of the clickable button.", "When Target ref is selected, locator visibility/contains/index fields no longer apply."],
  },
  find_element: {
    title: "Find Element Help",
    summary: "Resolve a matching element, filter/rank it by viewport, and store a short-lived ref for a later step such as Click.",
    useWhen: ["Use when many similar buttons exist in the DOM but you need the one currently in view.", "Use before Click with Target ref to separate element selection from clicking."],
    fields: [
      { name: "Target locator", description: "The real locator for candidate elements, such as all Like buttons inside articles." },
      { name: "Output name", description: "Runtime ref name that the next step can use through Target ref." },
      { name: "In viewport", description: "Required only selects elements intersecting the current viewport." },
      { name: "Rank", description: "Nearest viewport center chooses the candidate closest to screen center; Largest visible area chooses the most exposed candidate." },
    ],
    examples: ["Target locator: article button[aria-label^='Like video'][aria-pressed='false']", "Output name: current_like, Rank: Nearest viewport center"],
    commonMistakes: ["Using Target index instead of Rank can click the wrong post on scrolling or virtualized feeds.", "Turning In viewport off returns to first-DOM-match behavior."],
  },
  scroll: {
    title: "Scroll Help",
    summary: "Scroll the page by pixels, bring an existing element into view, or scroll to find a lazy-loaded element.",
    useWhen: ["Use Page Scroll for a fixed pixel-distance scroll.", "Use Scroll To Element when the element is already on the page but outside the viewport.", "Use Scroll Until Element Visible when page scrolling must trigger lazy-load DOM mounting."],
    fields: [
      { name: "Mode", description: "Page Scroll and target modes use gestures made of smaller wheel pulses, short pauses inside each gesture, and longer random pauses between gestures." },
      { name: "Scroll style", description: "Human-like splits Page Scroll into several pulses and pauses; Smooth single wheel sends one wheel gesture for the exact pixel distance." },
      { name: "Direction", description: "Page Scroll direction or Scroll Until Element Visible search direction: down, up, right, or left." },
      { name: "Pixels", description: "Pixel distance for Page Scroll or each search scroll. Try 250-800 depending on the page." },
      { name: "Target locator", description: "Target element for Scroll To Element or Scroll Until Element Visible." },
      { name: "Iframe XPath", description: "Selects the parent-page iframe when the target uses a legacy XPath inside a frame." },
      { name: "Timeout ms", description: scrollTimeoutField.en },
    ],
    examples: ["Mode: Page Scroll, Direction: Down, Pixels: 500", "Mode: Scroll To Element, Iframe XPath: //*[@id='main-frame'], Target locator: //h2[normalize-space(.)='Ready']", "Mode: Scroll Until Element Visible, Direction: Down, Pixels: 700, Target locator: lazy card"],
    commonMistakes: ["If the element is inside an iframe, set Iframe XPath for the iframe and the target locator inside that iframe.", "Scroll To Element needs the target to already exist in the DOM; use Scroll Until Element Visible for lazy-load pages.", "Target scroll calculates human-like chunks and pauses automatically."],
  },
  select_option: {
    title: "Select Option Help",
    summary: "Select an option from a native HTML select dropdown.",
    useWhen: ["Use for native dropdowns such as country, category, or status.", "Do not use for custom div dropdowns; those usually need Click steps."],
    fields: [
      { name: "XPath", description: "XPath of the select element, not the option." },
      { name: "Match by", description: "Label matches visible text; Value matches the option value attribute." },
      { name: "Value", description: "The label or value to select, depending on Match by." },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["XPath: //*[@name='country'], Match by: Label, Value: Vietnam"],
    commonMistakes: ["XPath points to an option instead of the select.", "Custom dropdowns that are not select elements need a different step."],
  },
  press_key: {
    title: "Press Key Help",
    summary: "Press one keyboard key.",
    useWhen: ["Use for Enter, Tab, Escape, or ArrowDown after another step.", "Use when the website reacts to keyboard input instead of clicks."],
    fields: [{ name: "Key", description: "The key name to press, for example Enter, Tab, Escape, ArrowDown." }],
    examples: ["Key: Enter", "Key: Escape"],
    commonMistakes: ["This presses one key; combinations like Control+S should use Hotkey."],
  },
  hotkey: {
    title: "Hotkey Help",
    summary: "Press a keyboard shortcut.",
    useWhen: ["Use for Ctrl+S, Ctrl+A, Cmd+K, Alt+Enter.", "Use when the web app has keyboard shortcuts."],
    fields: [{ name: "Keys", description: "Enter keys separated by +, for example Control+S or Meta+K." }],
    examples: ["Keys: Control+S", "Keys: Meta+K"],
    commonMistakes: ["On macOS, Command is usually Meta.", "Avoid unnecessary extra spaces."],
  },
  hover: {
    title: "Hover Help",
    summary: "Move the mouse over an element.",
    useWhen: ["Use to open hover menus, tooltips, or reveal hidden buttons.", "Use before Click when a button only appears after hover."],
    fields: [
      { name: "XPath", description: xpathField.en },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["XPath: //*[@aria-label='User menu']"],
    commonMistakes: ["Hover only moves the mouse; it does not click.", "If a menu opens by click, use Click instead of Hover."],
  },
  get_current_url: {
    title: "Get Current URL Help",
    summary: "Capture the current page URL and store it in system.current_url.",
    useWhen: ["Use when you need the current URL, query params, or path segments."],
    fields: [
      { name: "Output", description: "URL data is stored in system.current_url with fields: href, origin, protocol, hostname, port, pathname, search, hash, params, segments, base." },
    ],
    examples: [],
    commonMistakes: ["Make sure the page has finished navigating before capturing the URL."],
  },
};

export const phaseOneEnglishStepHelpContent: Record<string, StepHelpContent> = {
  double_click: elementHelpEn("Double Click", "double click", "double-click"),
  right_click: elementHelpEn("Right Click", "right click", "context menu"),
  focus_element: elementHelpEn("Focus Element", "focus", "keyboard input"),
  blur_element: elementHelpEn("Blur Element", "blur", "validation"),
  paste_clipboard: elementHelpEn("Paste Into Field", "paste clipboard text into a field", "paste"),
  check: elementHelpEn("Check", "ensure a checkbox is checked", "checkbox"),
  uncheck: elementHelpEn("Uncheck", "ensure a checkbox is unchecked", "checkbox"),
  toggle_checkbox: elementHelpEn("Toggle Checkbox", "toggle a checkbox", "checkbox"),
  select_radio: elementHelpEn("Select Radio", "select a radio option", "radio"),
  upload_file: elementHelpEn("Upload File", "upload local files", "file"),
  submit_form: elementHelpEn("Submit Form", "submit a form", "submit"),
  select_custom_option: elementHelpEn("Select Custom Option", "select a custom dropdown option", "combobox"),
  set_contenteditable: elementHelpEn("Set Contenteditable", "set rich text content", "editor"),
  extract_text: elementHelpEn("Extract Text", "capture visible text", "output"),
  extract_attribute: elementHelpEn("Extract Attribute", "capture an element attribute", "output"),
  extract_input_value: elementHelpEn("Extract Input Value", "capture an input value", "output"),
  extract_table: elementHelpEn("Extract Table", "capture table rows", "output"),
  extract_list: elementHelpEn("Extract List", "capture list items", "output"),
  count_elements: elementHelpEn("Count Elements", "count matching elements", "output"),
  extract_regex_matches: {
    title: "Extract Regex Matches Help",
    summary: "Read an existing output, collect regex matches, and save the matches into a new or existing output.",
    useWhen: ["Use after Extract Text or Extract List when you need URLs, usernames, order ids, or tokens from captured text."],
    fields: [
      { name: "Source output", description: "Input output name to read, such as post_text or comment_text." },
      { name: "Pattern", description: "Regex pattern used to find matches in the source output." },
      { name: "Flags", description: "Regex flags such as g, i, m; g is used so multiple matches can be collected." },
      { name: "Output name", description: "Output name that stores the match list." },
      { name: "Append", description: "Enable to add matches to an existing output list instead of replacing it." },
      { name: "Dedupe", description: "Enable to keep each matched value once in the output list." },
    ],
    examples: ["Source output: comment_text, Pattern: @[A-Za-z0-9._-]+, Output name: tiktok_targets"],
    commonMistakes: ["Invalid regex syntax fails validation.", "Turning Append off inside a loop keeps only the last loop result."],
  },
  go_back: elementHelpEn("Go Back", "go back in browser history", "history"),
  go_forward: elementHelpEn("Go Forward", "go forward in browser history", "history"),
  reload: elementHelpEn("Reload", "reload the current tab", "browser"),
  open_new_tab: elementHelpEn("Open New Tab", "open a new browser tab", "tab"),
  switch_tab: elementHelpEn("Switch Tab", "switch to another browser tab", "tab"),
  close_tab: elementHelpEn("Close Tab", "close a browser tab", "tab"),
  accept_dialog: elementHelpEn("Accept Dialog", "accept an alert, confirm, or prompt", "dialog"),
  dismiss_dialog: elementHelpEn("Dismiss Dialog", "dismiss an alert, confirm, or prompt", "dialog"),
  wait_for_download: elementHelpEn("Wait For Download", "wait until a new downloaded file exists", "download"),
  write_text_file: {
    title: "Write Text File Help",
    summary: "Write an output as a text file inside the run evidence directory and store the artifact path in an output.",
    useWhen: ["Use at the end of a workflow to export captured URLs, usernames, short logs, or collected data."],
    fields: [
      { name: "Source output", description: "Output name to write into the file." },
      { name: "Path", description: "Safe artifact file name, for example tiktok-usernames.txt." },
      { name: "Separator", description: "String used between array items; use \\n for one item per line." },
      { name: "Trailing newline", description: "Enable to append a final newline to the file." },
      { name: "Output name", description: "Output name that stores the evidence-relative file path." },
    ],
    examples: ["Source output: tiktok_targets, Path: tiktok-usernames.txt, Output name: tiktok_username_file"],
    commonMistakes: ["Path is only an artifact file name, not a filesystem path.", "An empty source output creates an empty file."],
  },
  set_variable: elementHelpEn("Set Variables", "save reusable values", "variable"),
  set_json_variables: elementHelpEn("Set JSON Variables", "save structured JSON values", "variable"),
  update_number_variable: variableHelpEn("Update Number Variable", "perform math operations on a number variable"),
  update_text_variable: variableHelpEn("Update Text Variable", "perform string operations on a text variable"),
  update_flag_variable: variableHelpEn("Update Flag Variable", "update boolean flag variable"),
  update_list_variable: variableHelpEn("Update List Variable", "perform array operations on a list variable"),
  update_object_variable: variableHelpEn("Update Object Variable", "perform JSON object operations on an object variable"),
  assert_element: elementHelpEn("Assert Element", "require an element state", "assert"),
  assert_text: elementHelpEn("Assert Text", "require expected text", "assert"),
  graph_noop: elementHelpEn("Graph No-op", "mark internal graph flow progress", "logic"),
  if_condition: elementHelpEn("If Condition", "run steps when a condition matches", "logic"),
  router_condition: elementHelpEn("Router Condition", "run first matching router case", "logic"),
  random_choice: elementHelpEn("Random Choice", "choose one weighted branch", "logic"),
  repeat_times: elementHelpEn("Repeat Times", "repeat nested steps", "loop"),
  repeat_for_each: elementHelpEn("Repeat For Each", "repeat steps for each item", "loop"),
  retry_block: elementHelpEn("Retry Block", "retry nested steps after failure", "retry"),
  stop_workflow: elementHelpEn("Stop Workflow", "stop the workflow intentionally", "stop"),
  set_cookie: elementHelpEn("Set Cookie", "set a visible browser cookie", "cookie"),
  clear_cookies: elementHelpEn("Clear Cookies", "clear visible browser cookies", "cookie"),
  set_viewport: elementHelpEn("Set Viewport", "set runtime viewport size", "device"),
  set_geolocation: elementHelpEn("Set Geolocation", "override browser geolocation", "geo"),
  set_extra_headers: elementHelpEn("Set Extra Headers", "send extra HTTP headers", "headers"),
  grant_permission: elementHelpEn("Grant Permission", "grant browser permissions", "permission"),
  execute_js: elementHelpEn("Execute JS", "run advanced JavaScript", "advanced"),
  wait_for_request: elementHelpEn("Wait For Request", "wait for a network request", "network"),
  wait_for_response: elementHelpEn("Wait For Response", "wait for a network response", "network"),
  block_request: elementHelpEn("Block Request", "block matching fetch requests", "network"),
  mock_response: elementHelpEn("Mock Response", "mock a matching fetch response", "network"),
  set_local_storage: elementHelpEn("Set Local Storage", "set localStorage", "storage"),
  set_session_storage: elementHelpEn("Set Session Storage", "set sessionStorage", "storage"),
  take_screenshot: {
    title: "Take Screenshot Help",
    summary: "Capture the current page and save the path into outputs when Output name is set.",
    useWhen: ["Use to keep visual evidence after an important workflow action."],
    fields: [
      { name: "Path", description: "PNG file path to write." },
      { name: "Output name", description: "Output variable name that stores the screenshot path." },
      { name: "Full page", description: "Yes captures the full page; No captures the current viewport." },
    ],
    examples: ["Path: /tmp/workflow-result.png, Output name: screenshot_path"],
    commonMistakes: ["The parent folder of Path must exist.", "An existing file at the same path is overwritten."],
  },
  drag_and_drop: {
    title: "Drag and Drop Help",
    summary: "Drag a source element and drop it onto a target element.",
    useWhen: ["Use for reordering cards, moving items into drop zones, or kanban-style UIs."],
    fields: [
      { name: "Source selection", description: "Choose a direct locator or Find Element ref for the element to drag." },
      { name: "Source ref", description: "Find Element output name when Drag source uses a runtime ref." },
      { name: "Source locator", description: "Locator for the element to drag." },
      { name: "Drop target source", description: "Choose a direct locator or Find Element ref for the destination element or area." },
      { name: "Drop target ref", description: "Find Element output name when Drop target uses a runtime ref." },
      { name: "Target locator", description: "Locator for the drop target element or area." },
      { name: "Destination position", description: "Drop point inside the target: target center, percent inside the target, or pixel offset from the target's top-left corner." },
      { name: "X percent", description: "Horizontal coordinate inside the target when Destination position is Percent inside target." },
      { name: "Y percent", description: "Vertical coordinate inside the target when Destination position is Percent inside target." },
      { name: "X offset px", description: "Horizontal pixels from the target's top-left corner when using Pixel offset." },
      { name: "Y offset px", description: "Vertical pixels from the target's top-left corner when using Pixel offset." },
    ],
    examples: ["Source locator: card-1, Target locator: done-lane", "Destination position: Percent inside target, X percent: 82, Y percent: 50"],
    commonMistakes: ["Source and target should be the right elements for their roles, such as the draggable thumb and the track/drop zone.", "Sliders usually need Percent inside target instead of Center of target."],
  },
  type_sequence: {
    title: "Type Sequence Help",
    summary: "Type text character by character with keyboard-like events.",
    useWhen: ["Use for autocomplete, command palettes, rich text editors, or fields that depend on key events."],
    fields: [
      { name: "XPath", description: xpathField.en },
      { name: "Text", description: "The characters to type." },
      { name: "Delay ms", description: "Delay between characters." },
      { name: "Iframe XPath", description: iframeField.en },
      { name: "Wait until", description: waitUntilField.en },
      { name: "Timeout ms", description: timeoutField.en },
    ],
    examples: ["XPath: //*[@role='combobox'], Text: apple, Delay ms: 25"],
    commonMistakes: ["Fill Field is faster and more stable for normal fields.", "Delay 0 is invalid; leave it blank when no delay is needed."],
  },
  set_clipboard: {
    title: "Set Clipboard Help",
    summary: "Set the workflow clipboard text for a later Paste Into Field step.",
    useWhen: ["Use when the site handles paste better than typing.", "Use before Paste Into Field."],
    fields: [{ name: "Text", description: "The text to place into the workflow clipboard." }],
    examples: ["Text: Text to paste"],
    commonMistakes: ["This only prepares the text; use Paste Into Field to put it into a field."],
  },
};
