import type { ActionType } from "../../../types/workflow";
import { actionLabels } from "../../../lib/workflowUi";
import type {
  BilingualStepHelp,
} from "./stepHelpTypes";
import { enrichStepHelpContent } from "./stepHelpEnrichment";
import { englishStepHelpContent, phaseOneEnglishStepHelpContent } from "./stepHelpContent.en";
import { vietnameseStepHelpContent, phaseOneVietnameseStepHelpContent } from "./stepHelpContent.vi";

const graphInternalActionTypes = [
  "graph_noop",
  "switch_condition",
  "router_condition",
  "while_loop",
  "repeat_until",
  "try_catch",
  "fallback_block",
  "break_loop",
  "continue_loop",
  "transform_variable",
  "assert_output",
  "domain_allowlist",
  "check_conditions",
  "calculate_value",
] as const satisfies readonly ActionType[];

type GraphInternalActionType = (typeof graphInternalActionTypes)[number];

const graphInternalStepHelpContent = Object.fromEntries(
  graphInternalActionTypes.map((actionType) => [
    actionType,
    graphInternalHelp(actionLabels[actionType]),
  ]),
) as Record<GraphInternalActionType, BilingualStepHelp>;

function graphInternalHelp(label: string): BilingualStepHelp {
  return {
    vi: {
      title: `Trợ giúp ${label}`,
      summary:
        "Action nội bộ do graph compiler tạo ra từ node logic hoặc node điều phối đã lưu.",
      useWhen: [
        "Giữ workflow cũ tương thích khi payload đã chứa action nội bộ này.",
        "Ưu tiên chỉnh logic bằng graph node tương ứng thay vì thêm action này trực tiếp.",
      ],
      fields: [{ name: "Config", description: "Cấu hình được sinh từ graph node tương ứng." }],
      examples: [`${label}: được tạo khi graph compile workflow.`],
      commonMistakes: ["Thêm trực tiếp action nội bộ thay vì dùng node graph dễ làm workflow khó đọc."],
    },
    en: {
      title: `${label} Help`,
      summary:
        "Internal executable action generated by the graph compiler from saved logic or orchestration nodes.",
      useWhen: [
        "Keep older workflows compatible when a payload already contains this internal action.",
        "Prefer editing the matching graph node instead of adding this action directly.",
      ],
      fields: [{ name: "Config", description: "Configuration generated from the matching graph node." }],
      examples: [`${label}: generated when the graph compiles the workflow.`],
      commonMistakes: ["Adding internal actions directly makes workflows harder to reason about."],
    },
  };
}

const mergedStepHelpContent: Record<ActionType, BilingualStepHelp> = {} as any;

// Populate baseStepHelpContent
for (const key of Object.keys(englishStepHelpContent) as ActionType[]) {
  mergedStepHelpContent[key] = {
    vi: vietnameseStepHelpContent[key],
    en: englishStepHelpContent[key],
  };
}

// Populate phaseOneStepHelpContent
for (const key of Object.keys(phaseOneEnglishStepHelpContent) as ActionType[]) {
  mergedStepHelpContent[key] = {
    vi: phaseOneVietnameseStepHelpContent[key],
    en: phaseOneEnglishStepHelpContent[key],
  };
}

// Populate graphInternalStepHelpContent
for (const key of Object.keys(graphInternalStepHelpContent) as ActionType[]) {
  mergedStepHelpContent[key] = graphInternalStepHelpContent[key as GraphInternalActionType];
}

export const stepHelpContent: Record<ActionType, BilingualStepHelp> =
  enrichStepHelpContent(mergedStepHelpContent);
