services:
  postgres:
    image: postgres:16-alpine
    container_name: automation-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev-automation-app
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: automation-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: automation_app
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
