#!/usr/bin/env node
// Vendor the brand webfonts the design tokens ask for.
//
// src/styles/base.css declares --font-display / --font-body / --font-mono as
// Plus Jakarta Sans / Inter / JetBrains Mono, but the app ships no font files
// and renders in system fallbacks. design-sync flags that ([FONT_MISSING]),
// because every design built with this DS would inherit the fallback. This
// downloads the latin subsets from Google Fonts and writes a local @font-face
// sheet that cfg.extraFonts points at.
//
// All three families are SIL Open Font License 1.1 — redistribution with the
// license file is permitted. Output (fonts/*.woff2 + fonts.css + OFL.txt) is
// committed; re-run only to add a weight or refresh the files.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = join(dirname(fileURLToPath(import.meta.url)), 'fonts');

// All three ship as variable fonts, so a weight RANGE costs exactly one file
// per family — asking for discrete weights returns the same woff2 four times
// over. The ranges cover the steps the token set actually uses (body text and
// its emphasis steps, semibold/bold display headings, regular/medium mono)
// with headroom either side.
const FAMILIES = [
  { name: 'Inter', range: '400..700' },
  { name: 'Plus Jakarta Sans', range: '400..800' },
  { name: 'JetBrains Mono', range: '400..700' },
];

// Google Fonts serves woff2 only to UAs known to support it.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const slug = (s) => s.replace(/\s+/g, '');

async function get(url, as = 'text') {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return as === 'text' ? res.text() : Buffer.from(await res.arrayBuffer());
}

mkdirSync(OUT, { recursive: true });
const rules = [];

for (const { name, range } of FAMILIES) {
  const api =
    `https://fonts.googleapis.com/css2?family=${encodeURIComponent(name)}:wght@` +
    `${range}&display=swap`;
  const css = await get(api);

  // The response is a run of @font-face blocks, each preceded by a
  // `/* <subset> */` comment. Keep the plain `latin` subset only — latin-ext
  // and the rest would multiply the committed bytes for no visible gain here.
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  const latin = blocks.filter(([, subset]) => subset === 'latin');
  if (latin.length !== 1) {
    throw new Error(`expected exactly one latin @font-face for ${name}, got ${latin.length}`);
  }

  const block = latin[0][2];
  const weight = /font-weight:\s*([\d\s]+);/.exec(block)?.[1]?.trim();
  const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
  const unicode = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
  if (!weight || !url) throw new Error(`unparsable @font-face for ${name}:\n${block}`);

  const file = `${slug(name)}.woff2`;
  const bytes = await get(url, 'buffer');
  writeFileSync(join(OUT, file), bytes);
  rules.push(
    [
      '@font-face {',
      `  font-family: "${name}";`,
      '  font-style: normal;',
      `  font-weight: ${weight};`,
      '  font-display: swap;',
      `  src: url("./${file}") format("woff2");`,
      ...(unicode ? [`  unicode-range: ${unicode};`] : []),
      '}',
    ].join('\n'),
  );
  console.error(`  ${name} ${weight} → fonts/${file} (${(bytes.length / 1024).toFixed(0)} KB)`);
}

writeFileSync(
  join(OUT, 'fonts.css'),
  [
    '/* Generated by .design-sync/fetch-fonts.mjs — do not hand-edit.',
    '   Brand faces named by src/styles/base.css (--font-display / --font-body /',
    '   --font-mono), vendored so designs built with this DS render in the real',
    '   typography instead of a system fallback. SIL OFL 1.1 — see OFL.txt. */',
    '',
    ...rules,
    '',
  ].join('\n'),
);

writeFileSync(
  join(OUT, 'OFL.txt'),
  [
    'Inter, Plus Jakarta Sans and JetBrains Mono are licensed under the',
    'SIL Open Font License, Version 1.1.',
    '',
    'Full license text: https://openfontlicense.org/open-font-license-official-text/',
    '',
    'Upstream sources:',
    '  Inter              https://fonts.google.com/specimen/Inter',
    '  Plus Jakarta Sans  https://fonts.google.com/specimen/Plus+Jakarta+Sans',
    '  JetBrains Mono     https://fonts.google.com/specimen/JetBrains+Mono',
    '',
  ].join('\n'),
);

console.error(`✓ ${rules.length} @font-face rule(s) → .design-sync/fonts/fonts.css`);
