export const workflowIpcChannels = {
  listWorkflows: "workflow:listWorkflows",
  getWorkflow: "workflow:getWorkflow",
  getWorkflowBrowserConfig: "workflow:getWorkflowBrowserConfig",
  saveWorkflowBrowserConfig: "workflow:saveWorkflowBrowserConfig",
  getWorkflowSettings: "workflow:getWorkflowSettings",
  saveWorkflowSettings: "workflow:saveWorkflowSettings",
  saveWorkflowSettingsSection: "workflow:saveWorkflowSettingsSection",
  validateWorkflowSettings: "workflow:validateWorkflowSettings",
  validateWorkflowRun: "workflow:validateWorkflowRun",
  createWorkflow: "workflow:createWorkflow",
  renameWorkflow: "workflow:renameWorkflow",
  deleteWorkflow: "workflow:deleteWorkflow",
  duplicateWorkflow: "workflow:duplicateWorkflow",
  getWorkflowGraph: "workflow:getWorkflowGraph",
  saveWorkflowGraph: "workflow:saveWorkflowGraph",
  validateWorkflowGraph: "workflow:validateWorkflowGraph",
  compileWorkflowGraph: "workflow:compileWorkflowGraph",
  runWorkflow: "workflow:runWorkflow",
  runWorkflowFromNode: "workflow:runWorkflowFromNode",
  stopRun: "workflow:stopRun",
  getRunState: "workflow:getRunState",
  validateSchedule: "workflow:validateSchedule",
  exportWorkflow: "workflow:exportWorkflow",
  importWorkflow: "workflow:importWorkflow",
  exportWorkflowPackage: "workflow:exportWorkflowPackage",
  previewWorkflowPackage: "workflow:previewWorkflowPackage",
  importWorkflowPackage: "workflow:importWorkflowPackage",
  runBatchWorkflow: "workflow:runBatchWorkflow",
  suggestSelectors: "workflow:suggestSelectors",
  normalizeRecordedEvents: "workflow:normalizeRecordedEvents",
  dryRunValidateConfig: "workflow:dryRunValidateConfig",
  saveWorkflowPackageFile: "workflow:saveWorkflowPackageFile",
} as const;

export type WorkflowIpcChannelName = keyof typeof workflowIpcChannels;
