// @vitest-environment node

import { describe, expect, test } from "vitest";
import type { ActionConfig } from "../../../src/types/workflow";
import {
  assertActionExecutorCoverage,
  createActionExecutorMap,
  executeRegisteredAction,
} from "./execution";

describe("backend action execution registry", () => {
  test("dispatches action configs through a registry-covered execution handler", async () => {
    const calls: string[] = [];
    const executors = createActionExecutorMap({
      navigate: async (action) => calls.push(`navigate:${action.config.url}`),
      wait: async () => calls.push("wait"),
      random_wait: async () => calls.push("random_wait"),
      input_text: async () => calls.push("input_text"),
      clear_input: async () => calls.push("clear_input"),
      click: async () => calls.push("click"),
      find_element: async () => calls.push("find_element"),
      scroll: async () => calls.push("scroll"),
      select_option: async () => calls.push("select_option"),
      press_key: async () => calls.push("press_key"),
      hotkey: async () => calls.push("hotkey"),
      hover: async () => calls.push("hover"),
      double_click: async () => calls.push("double_click"),
      right_click: async () => calls.push("right_click"),
      drag_and_drop: async () => calls.push("drag_and_drop"),
      focus_element: async () => calls.push("focus_element"),
      blur_element: async () => calls.push("blur_element"),
      type_sequence: async () => calls.push("type_sequence"),
      set_clipboard: async () => calls.push("set_clipboard"),
      paste_clipboard: async () => calls.push("paste_clipboard"),
      check: async () => calls.push("check"),
      uncheck: async () => calls.push("uncheck"),
      toggle_checkbox: async () => calls.push("toggle_checkbox"),
      select_radio: async () => calls.push("select_radio"),
      upload_file: async () => calls.push("upload_file"),
      submit_form: async () => calls.push("submit_form"),
      select_custom_option: async () => calls.push("select_custom_option"),
      set_contenteditable: async () => calls.push("set_contenteditable"),
      extract_text: async () => calls.push("extract_text"),
      extract_attribute: async () => calls.push("extract_attribute"),
      extract_input_value: async () => calls.push("extract_input_value"),
      extract_table: async () => calls.push("extract_table"),
      extract_list: async () => calls.push("extract_list"),
      count_elements: async () => calls.push("count_elements"),
      extract_regex_matches: async () => calls.push("extract_regex_matches"),
      take_screenshot: async () => calls.push("take_screenshot"),
      write_text_file: async () => calls.push("write_text_file"),
      go_back: async () => calls.push("go_back"),
      go_forward: async () => calls.push("go_forward"),
      reload: async () => calls.push("reload"),
      open_new_tab: async () => calls.push("open_new_tab"),
      switch_tab: async () => calls.push("switch_tab"),
      close_tab: async () => calls.push("close_tab"),
      accept_dialog: async () => calls.push("accept_dialog"),
      dismiss_dialog: async () => calls.push("dismiss_dialog"),
      wait_for_download: async () => calls.push("wait_for_download"),
      set_variable: async () => calls.push("set_variable"),
      set_json_variables: async () => calls.push("set_json_variables"),
      assert_element: async () => calls.push("assert_element"),
      assert_text: async () => calls.push("assert_text"),
      graph_noop: async () => calls.push("graph_noop"),
      if_condition: async () => calls.push("if_condition"),
      router_condition: async () => calls.push("router_condition"),
      random_choice: async () => calls.push("random_choice"),
      repeat_times: async () => calls.push("repeat_times"),
      repeat_for_each: async () => calls.push("repeat_for_each"),
      retry_block: async () => calls.push("retry_block"),
      switch_condition: async () => calls.push("switch_condition"),
      while_loop: async () => calls.push("while_loop"),
      repeat_until: async () => calls.push("repeat_until"),
      try_catch: async () => calls.push("try_catch"),
      fallback_block: async () => calls.push("fallback_block"),
      break_loop: async () => calls.push("break_loop"),
      continue_loop: async () => calls.push("continue_loop"),
      stop_workflow: async () => calls.push("stop_workflow"),
      transform_variable: async () => calls.push("transform_variable"),
      update_number_variable: async () => calls.push("update_number_variable"),
      set_number_variable: async () => calls.push("set_number_variable"),
      generate_random_number: async () => calls.push("generate_random_number"),
      parse_text_to_number: async () => calls.push("parse_text_to_number"),
      math_operation: async () => calls.push("math_operation"),
      round_number: async () => calls.push("round_number"),
      format_number: async () => calls.push("format_number"),
      compare_numbers: async () => calls.push("compare_numbers"),
      check_number_range: async () => calls.push("check_number_range"),
      check_number_property: async () => calls.push("check_number_property"),
      update_text_variable: async () => calls.push("update_text_variable"),
      set_text_variable: async () => calls.push("set_text_variable"),
      append_text: async () => calls.push("append_text"),
      prepend_text: async () => calls.push("prepend_text"),
      replace_text: async () => calls.push("replace_text"),
      trim_text: async () => calls.push("trim_text"),
      change_text_case: async () => calls.push("change_text_case"),
      slice_text: async () => calls.push("slice_text"),
      regex_extract: async () => calls.push("regex_extract"),
      get_text_length: async () => calls.push("get_text_length"),
      check_text_empty: async () => calls.push("check_text_empty"),
      check_text_contains: async () => calls.push("check_text_contains"),
      check_text_regex_matches: async () => calls.push("check_text_regex_matches"),
      update_flag_variable: async () => calls.push("update_flag_variable"),
      update_list_variable: async () => calls.push("update_list_variable"),
      create_empty_list: async () => calls.push("create_empty_list"),
      create_list_manual: async () => calls.push("create_list_manual"),
      split_text_to_list: async () => calls.push("split_text_to_list"),
      generate_number_range: async () => calls.push("generate_number_range"),
      add_to_list: async () => calls.push("add_to_list"),
      remove_from_list_by_index: async () => calls.push("remove_from_list_by_index"),
      remove_from_list_by_value: async () => calls.push("remove_from_list_by_value"),
      merge_lists: async () => calls.push("merge_lists"),
      get_list_item: async () => calls.push("get_list_item"),
      get_list_length: async () => calls.push("get_list_length"),
      slice_list: async () => calls.push("slice_list"),
      join_list: async () => calls.push("join_list"),
      filter_list: async () => calls.push("filter_list"),
      map_list_property: async () => calls.push("map_list_property"),
      sort_reverse_list: async () => calls.push("sort_reverse_list"),
      execute_list_script: async () => calls.push("execute_list_script"),
      check_list_empty: async () => calls.push("check_list_empty"),
      check_list_contains: async () => calls.push("check_list_contains"),
      check_list_any_match: async () => calls.push("check_list_any_match"),
      check_list_all_match: async () => calls.push("check_list_all_match"),
      update_object_variable: async () => calls.push("update_object_variable"),
      create_empty_object: async () => calls.push("create_empty_object"),
      create_object_manual: async () => calls.push("create_object_manual"),
      parse_json_to_object: async () => calls.push("parse_json_to_object"),
      set_object_property: async () => calls.push("set_object_property"),
      remove_object_property: async () => calls.push("remove_object_property"),
      merge_objects: async () => calls.push("merge_objects"),
      rename_object_property: async () => calls.push("rename_object_property"),
      get_object_property: async () => calls.push("get_object_property"),
      get_object_keys: async () => calls.push("get_object_keys"),
      get_object_values: async () => calls.push("get_object_values"),
      stringify_object: async () => calls.push("stringify_object"),
      execute_object_script: async () => calls.push("execute_object_script"),
      check_object_key_exists: async () => calls.push("check_object_key_exists"),
      check_object_empty: async () => calls.push("check_object_empty"),
      assert_output: async () => calls.push("assert_output"),
      domain_allowlist: async () => calls.push("domain_allowlist"),
      set_cookie: async () => calls.push("set_cookie"),
      clear_cookies: async () => calls.push("clear_cookies"),
      set_viewport: async () => calls.push("set_viewport"),
      set_geolocation: async () => calls.push("set_geolocation"),
      set_extra_headers: async () => calls.push("set_extra_headers"),
      grant_permission: async () => calls.push("grant_permission"),
      execute_js: async (action) => calls.push(`execute_js:${action.config.script}`),
      wait_for_request: async () => calls.push("wait_for_request"),
      wait_for_response: async () => calls.push("wait_for_response"),
      block_request: async () => calls.push("block_request"),
      mock_response: async () => calls.push("mock_response"),
      set_local_storage: async () => calls.push("set_local_storage"),
      set_session_storage: async () => calls.push("set_session_storage"),
      get_current_url: async () => calls.push("get_current_url"),
      check_conditions: async () => calls.push("check_conditions"),
      calculate_value: async () => calls.push("calculate_value"),
      read_text_file: async () => calls.push("read_text_file"),
      parse_csv_excel: async () => calls.push("parse_csv_excel"),
      write_csv_excel: async () => calls.push("write_csv_excel"),
      file_operation: async () => calls.push("file_operation"),
      http_request: async () => calls.push("http_request"),
      date_time_operation: async () => calls.push("date_time_operation"),
      crypto_operation: async () => calls.push("crypto_operation"),
      switch_frame: async () => calls.push("switch_frame"),
      switch_to_parent_frame: async () => calls.push("switch_to_parent_frame"),
      quarantined: async () => calls.push("quarantined"),
    });

    assertActionExecutorCoverage(executors);
    await executeRegisteredAction(executors, {
      type: "execute_js",
      config: { script: "return 42", output_name: "answer" },
    });

    expect(calls).toEqual(["execute_js:return 42"]);
  });

  test("rejects unknown action configs before handler lookup", async () => {
    const executors = createActionExecutorMap({} as never);

    await expect(
      executeRegisteredAction(executors, {
        type: "legacy_action",
        config: {},
      } as ActionConfig),
    ).rejects.toThrow("Unsupported action type: legacy_action");
  });

  test("reports registered actions missing execution handlers", () => {
    expect(() => assertActionExecutorCoverage({ navigate: async () => undefined })).toThrow(
      "Action wait is registered without an execution handler",
    );
  });
});
