// @vitest-environment node

import { describe, expect, test } from "vitest";
import {
  actionDefinitions,
  getActionDefinition,
  isKnownActionType,
  unsupportedActionTypeMessage,
} from "./registry";

describe("backend action registry", () => {
  test("registers every serialized action type with execution ownership metadata", () => {
    expect(actionDefinitions.map((definition) => definition.type)).toEqual([
      "navigate",
      "wait",
      "random_wait",
      "input_text",
      "clear_input",
      "click",
      "find_element",
      "scroll",
      "select_option",
      "press_key",
      "hotkey",
      "hover",
      "double_click",
      "right_click",
      "drag_and_drop",
      "focus_element",
      "blur_element",
      "type_sequence",
      "set_clipboard",
      "paste_clipboard",
      "check",
      "uncheck",
      "toggle_checkbox",
      "select_radio",
      "upload_file",
      "submit_form",
      "select_custom_option",
      "set_contenteditable",
      "extract_text",
      "extract_attribute",
      "extract_input_value",
      "extract_table",
      "extract_list",
      "count_elements",
      "extract_regex_matches",
      "take_screenshot",
      "write_text_file",
      "go_back",
      "go_forward",
      "reload",
      "open_new_tab",
      "switch_tab",
      "close_tab",
      "accept_dialog",
      "dismiss_dialog",
      "wait_for_download",
      "set_variable",
      "set_json_variables",
      "check_conditions",
      "calculate_value",
      "assert_element",
      "assert_text",
      "graph_noop",
      "if_condition",
      "router_condition",
      "random_choice",
      "repeat_times",
      "repeat_for_each",
      "retry_block",
      "switch_condition",
      "while_loop",
      "repeat_until",
      "try_catch",
      "fallback_block",
      "break_loop",
      "continue_loop",
      "stop_workflow",
      "transform_variable",
      "update_number_variable",
      "set_number_variable",
      "generate_random_number",
      "parse_text_to_number",
      "math_operation",
      "round_number",
      "format_number",
      "compare_numbers",
      "check_number_range",
      "check_number_property",
      "update_text_variable",
      "set_text_variable",
      "append_text",
      "prepend_text",
      "replace_text",
      "trim_text",
      "change_text_case",
      "slice_text",
      "regex_extract",
      "get_text_length",
      "check_text_empty",
      "check_text_contains",
      "check_text_regex_matches",
      "update_flag_variable",
      "set_boolean_variable",
      "generate_random_boolean",
      "parse_to_boolean",
      "boolean_logical_op",
      "compare_booleans",
      "check_boolean_property",
      "update_list_variable",
      "create_empty_list",
      "create_list_manual",
      "split_text_to_list",
      "generate_number_range",
      "add_to_list",
      "remove_from_list_by_index",
      "remove_from_list_by_value",
      "merge_lists",
      "get_list_item",
      "get_list_length",
      "slice_list",
      "join_list",
      "filter_list",
      "map_list_property",
      "sort_reverse_list",
      "execute_list_script",
      "check_list_empty",
      "check_list_contains",
      "check_list_any_match",
      "check_list_all_match",
      "create_empty_object",
      "create_object_manual",
      "parse_json_to_object",
      "set_object_property",
      "remove_object_property",
      "merge_objects",
      "rename_object_property",
      "get_object_property",
      "get_object_keys",
      "get_object_values",
      "stringify_object",
      "execute_object_script",
      "check_object_key_exists",
      "check_object_empty",
      "assert_output",
      "domain_allowlist",
      "quarantined",
      "set_cookie",
      "clear_cookies",
      "set_viewport",
      "set_geolocation",
      "set_extra_headers",
      "grant_permission",
      "execute_js",
      "wait_for_request",
      "wait_for_response",
      "block_request",
      "mock_response",
      "set_local_storage",
      "set_session_storage",
      "get_current_url",
      "read_text_file",
      "parse_csv_excel",
      "write_csv_excel",
      "file_operation",
      "http_request",
      "date_time_operation",
      "crypto_operation",
      "switch_frame",
      "switch_to_parent_frame",
    ]);
    expect(getActionDefinition("execute_js")).toMatchObject({
      type: "execute_js",
      owner: "advanced",
      auditRisk: "high",
    });
    expect(getActionDefinition("if_condition")).toMatchObject({
      type: "if_condition",
      owner: "graph_internal",
      hiddenFromPalette: true,
    });
  });

  test("provides one unknown-action gate for compiler and runner defense", () => {
    expect(isKnownActionType("navigate")).toBe(true);
    expect(isKnownActionType("legacy_action")).toBe(false);
    expect(getActionDefinition("legacy_action")).toBeUndefined();
    expect(unsupportedActionTypeMessage("legacy_action")).toBe(
      "Unsupported action type: legacy_action",
    );
    expect(unsupportedActionTypeMessage("")).toBe("Unsupported action type: unknown");
  });
});
